
package com.huawei.ocs55.bcservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BcServices", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BcServices {


    /**
     * 
     * @param acctDeactivationRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.AcctDeactivationResultMsg
     */
    @WebMethod(operationName = "AcctDeactivation", action = "AcctDeactivation")
    @WebResult(name = "AcctDeactivationResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "AcctDeactivationResultMsg")
    public AcctDeactivationResultMsg acctDeactivation(
        @WebParam(name = "AcctDeactivationRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "AcctDeactivationRequestMsg")
        AcctDeactivationRequestMsg acctDeactivationRequestMsg);

    /**
     * 
     * @param changeSubOfferingRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.ChangeSubOfferingResultMsg
     */
    @WebMethod(operationName = "ChangeSubOffering", action = "ChangeSubOffering")
    @WebResult(name = "ChangeSubOfferingResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeSubOfferingResultMsg")
    public ChangeSubOfferingResultMsg changeSubOffering(
        @WebParam(name = "ChangeSubOfferingRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeSubOfferingRequestMsg")
        ChangeSubOfferingRequestMsg changeSubOfferingRequestMsg);

    /**
     * 
     * @param changeOfferingPropertyRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.ChangeOfferingPropertyResultMsg
     */
    @WebMethod(operationName = "ChangeOfferingProperty", action = "ChangeOfferingProperty")
    @WebResult(name = "ChangeOfferingPropertyResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeOfferingPropertyResultMsg")
    public ChangeOfferingPropertyResultMsg changeOfferingProperty(
        @WebParam(name = "ChangeOfferingPropertyRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeOfferingPropertyRequestMsg")
        ChangeOfferingPropertyRequestMsg changeOfferingPropertyRequestMsg);

    /**
     * 
     * @param queryOfferingInstPropertyRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.QueryOfferingInstPropertyResultMsg
     */
    @WebMethod(operationName = "QueryOfferingInstProperty", action = "QueryOfferingInstProperty")
    @WebResult(name = "QueryOfferingInstPropertyResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "QueryOfferingInstPropertyResultMsg")
    public QueryOfferingInstPropertyResultMsg queryOfferingInstProperty(
        @WebParam(name = "QueryOfferingInstPropertyRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "QueryOfferingInstPropertyRequestMsg")
        QueryOfferingInstPropertyRequestMsg queryOfferingInstPropertyRequestMsg);

    /**
     * 
     * @param queryCustomerInfoRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.QueryCustomerInfoResultMsg
     */
    @WebMethod(operationName = "QueryCustomerInfo", action = "QueryCustomerInfo")
    @WebResult(name = "QueryCustomerInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "QueryCustomerInfoResultMsg")
    public QueryCustomerInfoResultMsg queryCustomerInfo(
        @WebParam(name = "QueryCustomerInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "QueryCustomerInfoRequestMsg")
        QueryCustomerInfoRequestMsg queryCustomerInfoRequestMsg);

    /**
     * 
     * @param changeSubIdentityRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.ChangeSubIdentityResultMsg
     */
    @WebMethod(operationName = "ChangeSubIdentity", action = "ChangeSubIdentity")
    @WebResult(name = "ChangeSubIdentityResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeSubIdentityResultMsg")
    public ChangeSubIdentityResultMsg changeSubIdentity(
        @WebParam(name = "ChangeSubIdentityRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeSubIdentityRequestMsg")
        ChangeSubIdentityRequestMsg changeSubIdentityRequestMsg);

    /**
     * 
     * @param queryGroupListBySubscriberRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.QueryGroupListBySubscriberResultMsg
     */
    @WebMethod(operationName = "QueryGroupListBySubscriber", action = "QueryGroupListBySubscriber")
    @WebResult(name = "QueryGroupListBySubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "QueryGroupListBySubscriberResultMsg")
    public QueryGroupListBySubscriberResultMsg queryGroupListBySubscriber(
        @WebParam(name = "QueryGroupListBySubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "QueryGroupListBySubscriberRequestMsg")
        QueryGroupListBySubscriberRequestMsg queryGroupListBySubscriberRequestMsg);

    /**
     * 
     * @param createGroupRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.CreateGroupResultMsg
     */
    @WebMethod(operationName = "CreateGroup", action = "CreateGroup")
    @WebResult(name = "CreateGroupResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "CreateGroupResultMsg")
    public CreateGroupResultMsg createGroup(
        @WebParam(name = "CreateGroupRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "CreateGroupRequestMsg")
        CreateGroupRequestMsg createGroupRequestMsg);

    /**
     * 
     * @param groupDeactivationRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.GroupDeactivationResultMsg
     */
    @WebMethod(operationName = "GroupDeactivation", action = "GroupDeactivation")
    @WebResult(name = "GroupDeactivationResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "GroupDeactivationResultMsg")
    public GroupDeactivationResultMsg groupDeactivation(
        @WebParam(name = "GroupDeactivationRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "GroupDeactivationRequestMsg")
        GroupDeactivationRequestMsg groupDeactivationRequestMsg);

    /**
     * 
     * @param changeGroupOfferingRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.ChangeGroupOfferingResultMsg
     */
    @WebMethod(operationName = "ChangeGroupOffering", action = "ChangeGroupOffering")
    @WebResult(name = "ChangeGroupOfferingResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeGroupOfferingResultMsg")
    public ChangeGroupOfferingResultMsg changeGroupOffering(
        @WebParam(name = "ChangeGroupOfferingRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeGroupOfferingRequestMsg")
        ChangeGroupOfferingRequestMsg changeGroupOfferingRequestMsg);

    /**
     * 
     * @param addGroupMemberRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.AddGroupMemberResultMsg
     */
    @WebMethod(operationName = "AddGroupMember", action = "AddGroupMember")
    @WebResult(name = "AddGroupMemberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "AddGroupMemberResultMsg")
    public AddGroupMemberResultMsg addGroupMember(
        @WebParam(name = "AddGroupMemberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "AddGroupMemberRequestMsg")
        AddGroupMemberRequestMsg addGroupMemberRequestMsg);

    /**
     * 
     * @param delGroupMemberRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.DelGroupMemberResultMsg
     */
    @WebMethod(operationName = "DelGroupMember", action = "DelGroupMember")
    @WebResult(name = "DelGroupMemberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "DelGroupMemberResultMsg")
    public DelGroupMemberResultMsg delGroupMember(
        @WebParam(name = "DelGroupMemberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "DelGroupMemberRequestMsg")
        DelGroupMemberRequestMsg delGroupMemberRequestMsg);

    /**
     * 
     * @param changeGroupMemberInfoRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.ChangeGroupMemberInfoResultMsg
     */
    @WebMethod(operationName = "ChangeGroupMemberInfo", action = "ChangeGroupMemberInfo")
    @WebResult(name = "ChangeGroupMemberInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeGroupMemberInfoResultMsg")
    public ChangeGroupMemberInfoResultMsg changeGroupMemberInfo(
        @WebParam(name = "ChangeGroupMemberInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeGroupMemberInfoRequestMsg")
        ChangeGroupMemberInfoRequestMsg changeGroupMemberInfoRequestMsg);

    /**
     * 
     * @param changeGroupMemberOfferingRequestMsg
     * @return
     *     returns com.huawei.ocs55.bcservices.ChangeGroupMemberOfferingResultMsg
     */
    @WebMethod(operationName = "ChangeGroupMemberOffering", action = "ChangeGroupMemberOffering")
    @WebResult(name = "ChangeGroupMemberOfferingResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeGroupMemberOfferingResultMsg")
    public ChangeGroupMemberOfferingResultMsg changeGroupMemberOffering(
        @WebParam(name = "ChangeGroupMemberOfferingRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", partName = "ChangeGroupMemberOfferingRequestMsg")
        ChangeGroupMemberOfferingRequestMsg changeGroupMemberOfferingRequestMsg);

}
