
package com.huawei.ocs55.bcservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BcServices", targetNamespace = "http://www.huawei.com/bme/cbsinterface/bcservices", wsdlLocation = "file:/E:/OneDrive/09-tt/unieap/unieap-esb/src/main/resources/wsdl/ocs55/CBSInterface_BC_Services.wsdl")
public class BcServices_Service
    extends Service
{

    private final static URL BCSERVICES_WSDL_LOCATION;
    private final static WebServiceException BCSERVICES_EXCEPTION;
    private final static QName BCSERVICES_QNAME = new QName("http://www.huawei.com/bme/cbsinterface/bcservices", "BcServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/OneDrive/09-tt/unieap/unieap-esb/src/main/resources/wsdl/ocs55/CBSInterface_BC_Services.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BCSERVICES_WSDL_LOCATION = url;
        BCSERVICES_EXCEPTION = e;
    }

    public BcServices_Service() {
        super(__getWsdlLocation(), BCSERVICES_QNAME);
    }

    public BcServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BCSERVICES_QNAME, features);
    }

    public BcServices_Service(URL wsdlLocation) {
        super(wsdlLocation, BCSERVICES_QNAME);
    }

    public BcServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BCSERVICES_QNAME, features);
    }

    public BcServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BcServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BcServices
     */
    @WebEndpoint(name = "BcServicesPort")
    public BcServices getBcServicesPort() {
        return super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/bcservices", "BcServicesPort"), BcServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BcServices
     */
    @WebEndpoint(name = "BcServicesPort")
    public BcServices getBcServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/bcservices", "BcServicesPort"), BcServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BCSERVICES_EXCEPTION!= null) {
            throw BCSERVICES_EXCEPTION;
        }
        return BCSERVICES_WSDL_LOCATION;
    }

}
