
package com.huawei.ocs12.businessmgrservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CBSInterfaceBusinessMgrServicePortType", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CBSInterfaceBusinessMgrServicePortType {


    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.DisclaimMissingResultMsg
     */
    @WebMethod(operationName = "DisclaimMissing", action = "DisclaimMissing")
    @WebResult(name = "DisclaimMissingResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public DisclaimMissingResultMsg disclaimMissing(
        @WebParam(name = "DisclaimMissingRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        DisclaimMissingRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeAppendantProductResultMsg
     */
    @WebMethod(operationName = "ChangeAppendantProduct", action = "ChangeAppendantProduct")
    @WebResult(name = "ChangeAppendantProductResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeAppendantProductResultMsg changeAppendantProduct(
        @WebParam(name = "ChangeAppendantProductRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeAppendantProductRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ManSubFamilyNoResultMsg
     */
    @WebMethod(operationName = "ManSubFamilyNo", action = "ManSubFamilyNo")
    @WebResult(name = "ManSubFamilyNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ManSubFamilyNoResultMsg manSubFamilyNo(
        @WebParam(name = "ManSubFamilyNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ManSubFamilyNoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryLanguageInfResultMsg
     */
    @WebMethod(operationName = "QueryLanguageInf", action = "QueryLanguageInf")
    @WebResult(name = "QueryLanguageInfResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryLanguageInfResultMsg queryLanguageInf(
        @WebParam(name = "QueryLanguageInfRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryLanguageInfRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeServicesResultMsg
     */
    @WebMethod(operationName = "ChangeServices", action = "ChangeServices")
    @WebResult(name = "ChangeServicesResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeServicesResultMsg changeServices(
        @WebParam(name = "ChangeServicesRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeServicesRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ModifyPosUserStateResultMsg
     */
    @WebMethod(operationName = "ModifyPosUserState", action = "ModifyPosUserState")
    @WebResult(name = "ModifyPosUserStateResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ModifyPosUserStateResultMsg modifyPosUserState(
        @WebParam(name = "ModifyPosUserStateRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ModifyPosUserStateRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ManCUGInfoResultMsg
     */
    @WebMethod(operationName = "ManCUGInfo", action = "ManCUGInfo")
    @WebResult(name = "ManCUGInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ManCUGInfoResultMsg manCUGInfo(
        @WebParam(name = "ManCUGInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ManCUGInfoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.IntegrationEnquiryResultMsg
     */
    @WebMethod(operationName = "IntegrationEnquiry", action = "IntegrationEnquiry")
    @WebResult(name = "IntegrationEnquiryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public IntegrationEnquiryResultMsg integrationEnquiry(
        @WebParam(name = "IntegrationEnquiryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        IntegrationEnquiryRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryDefinedZonesInfoResultMsg
     */
    @WebMethod(operationName = "QueryDefinedZonesInfo", action = "QueryDefinedZonesInfo")
    @WebResult(name = "QueryDefinedZonesInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryDefinedZonesInfoResultMsg queryDefinedZonesInfo(
        @WebParam(name = "QueryDefinedZonesInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryDefinedZonesInfoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ManSubCallScreenNoResultMsg
     */
    @WebMethod(operationName = "ManSubCallScreenNo", action = "ManSubCallScreenNo")
    @WebResult(name = "ManSubCallScreenNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ManSubCallScreenNoResultMsg manSubCallScreenNo(
        @WebParam(name = "ManSubCallScreenNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ManSubCallScreenNoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryUserGroupResultMsg
     */
    @WebMethod(operationName = "QueryUserGroup", action = "QueryUserGroup")
    @WebResult(name = "QueryUserGroupResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryUserGroupResultMsg queryUserGroup(
        @WebParam(name = "QueryUserGroupRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryUserGroupRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryAccumulatedPassInfoResultMsg
     */
    @WebMethod(operationName = "QueryAccumulatedPassInfo", action = "QueryAccumulatedPassInfo")
    @WebResult(name = "QueryAccumulatedPassInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryAccumulatedPassInfoResultMsg queryAccumulatedPassInfo(
        @WebParam(name = "QueryAccumulatedPassInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryAccumulatedPassInfoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryAdjustValidityLogResultMsg
     */
    @WebMethod(operationName = "QueryAdjustValidityLog", action = "QueryAdjustValidityLog")
    @WebResult(name = "QueryAdjustValidityLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryAdjustValidityLogResultMsg queryAdjustValidityLog(
        @WebParam(name = "QueryAdjustValidityLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryAdjustValidityLogRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ModifyCFNoResultMsg
     */
    @WebMethod(operationName = "ModifyCFNo", action = "ModifyCFNo")
    @WebResult(name = "ModifyCFNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ModifyCFNoResultMsg modifyCFNo(
        @WebParam(name = "ModifyCFNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ModifyCFNoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.UpdateCUGListResultMsg
     */
    @WebMethod(operationName = "UpdateCUGList", action = "UpdateCUGList")
    @WebResult(name = "UpdateCUGListResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public UpdateCUGListResultMsg updateCUGList(
        @WebParam(name = "UpdateCUGListRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        UpdateCUGListRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QuerySubHomeZoneResultMsg
     */
    @WebMethod(operationName = "QuerySubHomeZone", action = "QuerySubHomeZone")
    @WebResult(name = "QuerySubHomeZoneResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QuerySubHomeZoneResultMsg querySubHomeZone(
        @WebParam(name = "QuerySubHomeZoneRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QuerySubHomeZoneRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.UnSubscribeAppendantProductExtResultMsg
     */
    @WebMethod(operationName = "UnSubscribeAppendantProductExt", action = "UnSubscribeAppendantProductExt")
    @WebResult(name = "UnSubscribeAppendantProductExtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public UnSubscribeAppendantProductExtResultMsg unSubscribeAppendantProductExt(
        @WebParam(name = "UnSubscribeAppendantProductExtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        UnSubscribeAppendantProductExtRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryPassInfoResultMsg
     */
    @WebMethod(operationName = "QueryPassInfo", action = "QueryPassInfo")
    @WebResult(name = "QueryPassInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryPassInfoResultMsg queryPassInfo(
        @WebParam(name = "QueryPassInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryPassInfoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.CheckOperatorPasswordResultMsg
     */
    @WebMethod(operationName = "CheckOperatorPassword", action = "CheckOperatorPassword")
    @WebResult(name = "CheckOperatorPasswordResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public CheckOperatorPasswordResultMsg checkOperatorPassword(
        @WebParam(name = "CheckOperatorPasswordRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        CheckOperatorPasswordRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.NewSubscriberExtResultMsg
     */
    @WebMethod(operationName = "NewSubscriberExt", action = "NewSubscriberExt")
    @WebResult(name = "NewSubscriberExtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public NewSubscriberExtResultMsg newSubscriberExt(
        @WebParam(name = "NewSubscriberExtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        NewSubscriberExtRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ManSubHomeZoneResultMsg
     */
    @WebMethod(operationName = "ManSubHomeZone", action = "ManSubHomeZone")
    @WebResult(name = "ManSubHomeZoneResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ManSubHomeZoneResultMsg manSubHomeZone(
        @WebParam(name = "ManSubHomeZoneRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ManSubHomeZoneRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.BindProductSubscriberNoResultMsg
     */
    @WebMethod(operationName = "BindProductSubscriberNo", action = "BindProductSubscriberNo")
    @WebResult(name = "BindProductSubscriberNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public BindProductSubscriberNoResultMsg bindProductSubscriberNo(
        @WebParam(name = "BindProductSubscriberNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        BindProductSubscriberNoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ClaimMissingResultMsg
     */
    @WebMethod(operationName = "ClaimMissing", action = "ClaimMissing")
    @WebResult(name = "ClaimMissingResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ClaimMissingResultMsg claimMissing(
        @WebParam(name = "ClaimMissingRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ClaimMissingRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeSIMResultMsg
     */
    @WebMethod(operationName = "ChangeSIM", action = "ChangeSIM")
    @WebResult(name = "ChangeSIMResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeSIMResultMsg changeSIM(
        @WebParam(name = "ChangeSIMRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeSIMRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ManGroupMemberResultMsg
     */
    @WebMethod(operationName = "ManGroupMember", action = "ManGroupMember")
    @WebResult(name = "ManGroupMemberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ManGroupMemberResultMsg manGroupMember(
        @WebParam(name = "ManGroupMemberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ManGroupMemberRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QuerySubLowBalPrtResultMsg
     */
    @WebMethod(operationName = "QuerySubLowBalPrt", action = "QuerySubLowBalPrt")
    @WebResult(name = "QuerySubLowBalPrtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QuerySubLowBalPrtResultMsg querySubLowBalPrt(
        @WebParam(name = "QuerySubLowBalPrtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QuerySubLowBalPrtRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.SubscribeAppendantProductResultMsg
     */
    @WebMethod(operationName = "SubscribeAppendantProduct", action = "SubscribeAppendantProduct")
    @WebResult(name = "SubscribeAppendantProductResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public SubscribeAppendantProductResultMsg subscribeAppendantProduct(
        @WebParam(name = "SubscribeAppendantProductRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        SubscribeAppendantProductRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ManPromotionPlanResultMsg
     */
    @WebMethod(operationName = "ManPromotionPlan", action = "ManPromotionPlan")
    @WebResult(name = "ManPromotionPlanResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ManPromotionPlanResultMsg manPromotionPlan(
        @WebParam(name = "ManPromotionPlanRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ManPromotionPlanRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryPassCapEventInfoResultMsg
     */
    @WebMethod(operationName = "QueryPassCapEventInfo", action = "QueryPassCapEventInfo")
    @WebResult(name = "QueryPassCapEventInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryPassCapEventInfoResultMsg queryPassCapEventInfo(
        @WebParam(name = "QueryPassCapEventInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryPassCapEventInfoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QuerySubCallScreenNoResultMsg
     */
    @WebMethod(operationName = "QuerySubCallScreenNo", action = "QuerySubCallScreenNo")
    @WebResult(name = "QuerySubCallScreenNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QuerySubCallScreenNoResultMsg querySubCallScreenNo(
        @WebParam(name = "QuerySubCallScreenNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QuerySubCallScreenNoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeCustBasicInforResultMsg
     */
    @WebMethod(operationName = "ChangeCustBasicInfor", action = "ChangeCustBasicInfor")
    @WebResult(name = "ChangeCustBasicInforResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeCustBasicInforResultMsg changeCustBasicInfor(
        @WebParam(name = "ChangeCustBasicInforRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeCustBasicInforRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.SuspendResultMsg
     */
    @WebMethod(operationName = "Suspend", action = "Suspend")
    @WebResult(name = "SuspendResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public SuspendResultMsg suspend(
        @WebParam(name = "SuspendRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        SuspendRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.DeleteRechageBlackResultMsg
     */
    @WebMethod(operationName = "DeleteRechageBlack", action = "DeleteRechageBlack")
    @WebResult(name = "DeleteRechageBlackResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public DeleteRechageBlackResultMsg deleteRechageBlack(
        @WebParam(name = "DeleteRechageBlackRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        DeleteRechageBlackRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeMainProdResultMsg
     */
    @WebMethod(operationName = "ChangeMainProd", action = "ChangeMainProd")
    @WebResult(name = "ChangeMainProdResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeMainProdResultMsg changeMainProd(
        @WebParam(name = "ChangeMainProdRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeMainProdRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.UpdateSubscriberSegmentationResultMsg
     */
    @WebMethod(operationName = "UpdateSubscriberSegmentation", action = "UpdateSubscriberSegmentation")
    @WebResult(name = "UpdateSubscriberSegmentationResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public UpdateSubscriberSegmentationResultMsg updateSubscriberSegmentation(
        @WebParam(name = "UpdateSubscriberSegmentationRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        UpdateSubscriberSegmentationRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangePasswordResultMsg
     */
    @WebMethod(operationName = "ChangePassword", action = "ChangePassword")
    @WebResult(name = "ChangePasswordResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangePasswordResultMsg changePassword(
        @WebParam(name = "ChangePasswordRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangePasswordRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeSubLowBalPrtResultMsg
     */
    @WebMethod(operationName = "ChangeSubLowBalPrt", action = "ChangeSubLowBalPrt")
    @WebResult(name = "ChangeSubLowBalPrtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeSubLowBalPrtResultMsg changeSubLowBalPrt(
        @WebParam(name = "ChangeSubLowBalPrtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeSubLowBalPrtRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QuerySubscribedGroupResultMsg
     */
    @WebMethod(operationName = "QuerySubscribedGroup", action = "QuerySubscribedGroup")
    @WebResult(name = "QuerySubscribedGroupResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QuerySubscribedGroupResultMsg querySubscribedGroup(
        @WebParam(name = "QuerySubscribedGroupRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QuerySubscribedGroupRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.BatchSubscribeAppProductResultMsg
     */
    @WebMethod(operationName = "BatchSubscribeAppProduct", action = "BatchSubscribeAppProduct")
    @WebResult(name = "BatchSubscribeAppProductResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public BatchSubscribeAppProductResultMsg batchSubscribeAppProduct(
        @WebParam(name = "BatchSubscribeAppProductRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        BatchSubscribeAppProductRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeOwnerResultMsg
     */
    @WebMethod(operationName = "ChangeOwner", action = "ChangeOwner")
    @WebResult(name = "ChangeOwnerResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeOwnerResultMsg changeOwner(
        @WebParam(name = "ChangeOwnerRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeOwnerRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QuerySubFamilyNoResultMsg
     */
    @WebMethod(operationName = "QuerySubFamilyNo", action = "QuerySubFamilyNo")
    @WebResult(name = "QuerySubFamilyNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QuerySubFamilyNoResultMsg querySubFamilyNo(
        @WebParam(name = "QuerySubFamilyNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QuerySubFamilyNoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ManParentChildResultMsg
     */
    @WebMethod(operationName = "ManParentChild", action = "ManParentChild")
    @WebResult(name = "ManParentChildResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ManParentChildResultMsg manParentChild(
        @WebParam(name = "ManParentChildRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ManParentChildRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ReNewSubscriberResultMsg
     */
    @WebMethod(operationName = "ReNewSubscriber", action = "ReNewSubscriber")
    @WebResult(name = "ReNewSubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ReNewSubscriberResultMsg reNewSubscriber(
        @WebParam(name = "ReNewSubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ReNewSubscriberRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ModifySubscriberValidityResultMsg
     */
    @WebMethod(operationName = "ModifySubscriberValidity", action = "ModifySubscriberValidity")
    @WebResult(name = "ModifySubscriberValidityResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ModifySubscriberValidityResultMsg modifySubscriberValidity(
        @WebParam(name = "ModifySubscriberValidityRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ModifySubscriberValidityRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.BatchOperationResultMsg
     */
    @WebMethod(operationName = "BatchOperation", action = "BatchOperation")
    @WebResult(name = "BatchOperationResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public BatchOperationResultMsg batchOperation(
        @WebParam(name = "BatchOperationRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        BatchOperationRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryPromotionPlanResultMsg
     */
    @WebMethod(operationName = "QueryPromotionPlan", action = "QueryPromotionPlan")
    @WebResult(name = "QueryPromotionPlanResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryPromotionPlanResultMsg queryPromotionPlan(
        @WebParam(name = "QueryPromotionPlanRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryPromotionPlanRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeSubscriberBasicInforResultMsg
     */
    @WebMethod(operationName = "ChangeSubscriberBasicInfor", action = "ChangeSubscriberBasicInfor")
    @WebResult(name = "ChangeSubscriberBasicInforResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeSubscriberBasicInforResultMsg changeSubscriberBasicInfor(
        @WebParam(name = "ChangeSubscriberBasicInforRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeSubscriberBasicInforRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeMSISDNResultMsg
     */
    @WebMethod(operationName = "ChangeMSISDN", action = "ChangeMSISDN")
    @WebResult(name = "ChangeMSISDNResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeMSISDNResultMsg changeMSISDN(
        @WebParam(name = "ChangeMSISDNRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeMSISDNRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryGroupMemberResultMsg
     */
    @WebMethod(operationName = "QueryGroupMember", action = "QueryGroupMember")
    @WebResult(name = "QueryGroupMemberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryGroupMemberResultMsg queryGroupMember(
        @WebParam(name = "QueryGroupMemberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryGroupMemberRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryCUGTypeResultMsg
     */
    @WebMethod(operationName = "QueryCUGType", action = "QueryCUGType")
    @WebResult(name = "QueryCUGTypeResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryCUGTypeResultMsg queryCUGType(
        @WebParam(name = "QueryCUGTypeRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryCUGTypeRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ModifySubscriberStateResultMsg
     */
    @WebMethod(operationName = "ModifySubscriberState", action = "ModifySubscriberState")
    @WebResult(name = "ModifySubscriberStateResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ModifySubscriberStateResultMsg modifySubscriberState(
        @WebParam(name = "ModifySubscriberStateRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ModifySubscriberStateRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.DeleteSubscriberExtResultMsg
     */
    @WebMethod(operationName = "DeleteSubscriberExt", action = "DeleteSubscriberExt")
    @WebResult(name = "DeleteSubscriberExtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public DeleteSubscriberExtResultMsg deleteSubscriberExt(
        @WebParam(name = "DeleteSubscriberExtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        DeleteSubscriberExtRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.CheckPasswordResultMsg
     */
    @WebMethod(operationName = "CheckPassword", action = "CheckPassword")
    @WebResult(name = "CheckPasswordResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public CheckPasswordResultMsg checkPassword(
        @WebParam(name = "CheckPasswordRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        CheckPasswordRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.DeleteSubscriberResultMsg
     */
    @WebMethod(operationName = "DeleteSubscriber", action = "DeleteSubscriber")
    @WebResult(name = "DeleteSubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public DeleteSubscriberResultMsg deleteSubscriber(
        @WebParam(name = "DeleteSubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        DeleteSubscriberRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QuerySubscriberServiceInfoResultMsg
     */
    @WebMethod(operationName = "QuerySubscriberServiceInfo", action = "QuerySubscriberServiceInfo")
    @WebResult(name = "QuerySubscriberServiceInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QuerySubscriberServiceInfoResultMsg querySubscriberServiceInfo(
        @WebParam(name = "QuerySubscriberServiceInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QuerySubscriberServiceInfoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryChildLimitResultMsg
     */
    @WebMethod(operationName = "QueryChildLimit", action = "QueryChildLimit")
    @WebResult(name = "QueryChildLimitResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryChildLimitResultMsg queryChildLimit(
        @WebParam(name = "QueryChildLimitRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryChildLimitRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryBasicInfoResultMsg
     */
    @WebMethod(operationName = "QueryBasicInfo", action = "QueryBasicInfo")
    @WebResult(name = "QueryBasicInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryBasicInfoResultMsg queryBasicInfo(
        @WebParam(name = "QueryBasicInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryBasicInfoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QuerySubscriberProductInfoResultMsg
     */
    @WebMethod(operationName = "QuerySubscriberProductInfo", action = "QuerySubscriberProductInfo")
    @WebResult(name = "QuerySubscriberProductInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QuerySubscriberProductInfoResultMsg querySubscriberProductInfo(
        @WebParam(name = "QuerySubscriberProductInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QuerySubscriberProductInfoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryInterActLogResultMsg
     */
    @WebMethod(operationName = "QueryInterActLog", action = "QueryInterActLog")
    @WebResult(name = "QueryInterActLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryInterActLogResultMsg queryInterActLog(
        @WebParam(name = "QueryInterActLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryInterActLogRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ReconnectResultMsg
     */
    @WebMethod(operationName = "Reconnect", action = "Reconnect")
    @WebResult(name = "ReconnectResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ReconnectResultMsg reconnect(
        @WebParam(name = "ReconnectRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ReconnectRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QueryCUGMembersResultMsg
     */
    @WebMethod(operationName = "QueryCUGMembers", action = "QueryCUGMembers")
    @WebResult(name = "QueryCUGMembersResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryCUGMembersResultMsg queryCUGMembers(
        @WebParam(name = "QueryCUGMembersRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryCUGMembersRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.BlockSubscriberResultMsg
     */
    @WebMethod(operationName = "BlockSubscriber", action = "BlockSubscriber")
    @WebResult(name = "BlockSubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public BlockSubscriberResultMsg blockSubscriber(
        @WebParam(name = "BlockSubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        BlockSubscriberRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ResetPasswordResultMsg
     */
    @WebMethod(operationName = "ResetPassword", action = "ResetPassword")
    @WebResult(name = "ResetPasswordResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ResetPasswordResultMsg resetPassword(
        @WebParam(name = "ResetPasswordRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ResetPasswordRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.CheckUVCPartPinResultMsg
     */
    @WebMethod(operationName = "CheckUVCPartPin", action = "CheckUVCPartPin")
    @WebResult(name = "CheckUVCPartPinResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public CheckUVCPartPinResultMsg checkUVCPartPin(
        @WebParam(name = "CheckUVCPartPinRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        CheckUVCPartPinRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.QuerySubChangeLogResultMsg
     */
    @WebMethod(operationName = "QuerySubChangeLog", action = "QuerySubChangeLog")
    @WebResult(name = "QuerySubChangeLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QuerySubChangeLogResultMsg querySubChangeLog(
        @WebParam(name = "QuerySubChangeLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QuerySubChangeLogRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeAccountBasicInforResultMsg
     */
    @WebMethod(operationName = "ChangeAccountBasicInfor", action = "ChangeAccountBasicInfor")
    @WebResult(name = "ChangeAccountBasicInforResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeAccountBasicInforResultMsg changeAccountBasicInfor(
        @WebParam(name = "ChangeAccountBasicInforRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeAccountBasicInforRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.UnSubscribeAppendantProductResultMsg
     */
    @WebMethod(operationName = "UnSubscribeAppendantProduct", action = "UnSubscribeAppendantProduct")
    @WebResult(name = "UnSubscribeAppendantProductResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public UnSubscribeAppendantProductResultMsg unSubscribeAppendantProduct(
        @WebParam(name = "UnSubscribeAppendantProductRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        UnSubscribeAppendantProductRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.SynDTDiscountResultMsg
     */
    @WebMethod(operationName = "SynDTDiscount", action = "SynDTDiscount")
    @WebResult(name = "SynDTDiscountResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public SynDTDiscountResultMsg synDTDiscount(
        @WebParam(name = "SynDTDiscountRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        SynDTDiscountRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.NewSubscriberResultMsg
     */
    @WebMethod(operationName = "NewSubscriber", action = "NewSubscriber")
    @WebResult(name = "NewSubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public NewSubscriberResultMsg newSubscriber(
        @WebParam(name = "NewSubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        NewSubscriberRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.businessmgrservice.ChangeCreditLevelResultMsg
     */
    @WebMethod(operationName = "ChangeCreditLevel", action = "ChangeCreditLevel")
    @WebResult(name = "ChangeCreditLevelResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public ChangeCreditLevelResultMsg changeCreditLevel(
        @WebParam(name = "ChangeCreditLevelRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        ChangeCreditLevelRequestMsg part1);

}
