
package com.huawei.ocs55.businessmgr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CBSInterfaceBusinessMgrService", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgr", wsdlLocation = "file:/E:/OneDrive/09-tt/unieap/unieap-esb/src/main/resources/wsdl/ocs55/CBSInterface_BusinessMgr.wsdl")
public class CBSInterfaceBusinessMgrService
    extends Service
{

    private final static URL CBSINTERFACEBUSINESSMGRSERVICE_WSDL_LOCATION;
    private final static WebServiceException CBSINTERFACEBUSINESSMGRSERVICE_EXCEPTION;
    private final static QName CBSINTERFACEBUSINESSMGRSERVICE_QNAME = new QName("http://www.huawei.com/bme/cbsinterface/cbs/businessmgr", "CBSInterfaceBusinessMgrService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/OneDrive/09-tt/unieap/unieap-esb/src/main/resources/wsdl/ocs55/CBSInterface_BusinessMgr.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CBSINTERFACEBUSINESSMGRSERVICE_WSDL_LOCATION = url;
        CBSINTERFACEBUSINESSMGRSERVICE_EXCEPTION = e;
    }

    public CBSInterfaceBusinessMgrService() {
        super(__getWsdlLocation(), CBSINTERFACEBUSINESSMGRSERVICE_QNAME);
    }

    public CBSInterfaceBusinessMgrService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CBSINTERFACEBUSINESSMGRSERVICE_QNAME, features);
    }

    public CBSInterfaceBusinessMgrService(URL wsdlLocation) {
        super(wsdlLocation, CBSINTERFACEBUSINESSMGRSERVICE_QNAME);
    }

    public CBSInterfaceBusinessMgrService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CBSINTERFACEBUSINESSMGRSERVICE_QNAME, features);
    }

    public CBSInterfaceBusinessMgrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CBSInterfaceBusinessMgrService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CBSInterfaceBusinessMgr
     */
    @WebEndpoint(name = "CBSInterfaceBusinessMgrServicePort")
    public CBSInterfaceBusinessMgr getCBSInterfaceBusinessMgrServicePort() {
        return super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/cbs/businessmgr", "CBSInterfaceBusinessMgrServicePort"), CBSInterfaceBusinessMgr.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CBSInterfaceBusinessMgr
     */
    @WebEndpoint(name = "CBSInterfaceBusinessMgrServicePort")
    public CBSInterfaceBusinessMgr getCBSInterfaceBusinessMgrServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/cbs/businessmgr", "CBSInterfaceBusinessMgrServicePort"), CBSInterfaceBusinessMgr.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CBSINTERFACEBUSINESSMGRSERVICE_EXCEPTION!= null) {
            throw CBSINTERFACEBUSINESSMGRSERVICE_EXCEPTION;
        }
        return CBSINTERFACEBUSINESSMGRSERVICE_WSDL_LOCATION;
    }

}
