
package com.huawei.ocs55.businessmgr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CBSInterfaceBusinessMgr", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CBSInterfaceBusinessMgr {


    /**
     * 
     * @param queryBasicInfoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryBasicInfoResultMsg
     */
    @WebMethod(operationName = "QueryBasicInfo", action = "QueryBasicInfo")
    @WebResult(name = "QueryBasicInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryBasicInfoResultMsg")
    public QueryBasicInfoResultMsg queryBasicInfo(
        @WebParam(name = "QueryBasicInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryBasicInfoRequestMsg")
        QueryBasicInfoRequestMsg queryBasicInfoRequestMsg);

    /**
     * 
     * @param tariffEnquiryBySubscriberRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.TariffEnquiryBySubscriberResultMsg
     */
    @WebMethod(operationName = "TariffEnquiryBySubscriber", action = "TariffEnquiryBySubscriber")
    @WebResult(name = "TariffEnquiryBySubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "TariffEnquiryBySubscriberResultMsg")
    public TariffEnquiryBySubscriberResultMsg tariffEnquiryBySubscriber(
        @WebParam(name = "TariffEnquiryBySubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "TariffEnquiryBySubscriberRequestMsg")
        TariffEnquiryBySubscriberRequestMsg tariffEnquiryBySubscriberRequestMsg);

    /**
     * 
     * @param queryPaymentPlanRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryPaymentPlanResultMsg
     */
    @WebMethod(operationName = "QueryPaymentPlan", action = "QueryPaymentPlan")
    @WebResult(name = "QueryPaymentPlanResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryPaymentPlanResultMsg")
    public QueryPaymentPlanResultMsg queryPaymentPlan(
        @WebParam(name = "QueryPaymentPlanRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryPaymentPlanRequestMsg")
        QueryPaymentPlanRequestMsg queryPaymentPlanRequestMsg);

    /**
     * 
     * @param checkPasswordRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.CheckPasswordResultMsg
     */
    @WebMethod(operationName = "CheckPassword", action = "CheckPassword")
    @WebResult(name = "CheckPasswordResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "CheckPasswordResultMsg")
    public CheckPasswordResultMsg checkPassword(
        @WebParam(name = "CheckPasswordRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "CheckPasswordRequestMsg")
        CheckPasswordRequestMsg checkPasswordRequestMsg);

    /**
     * 
     * @param newSubscriberRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.NewSubscriberResultMsg
     */
    @WebMethod(operationName = "NewSubscriber", action = "NewSubscriber")
    @WebResult(name = "NewSubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "NewSubscriberResultMsg")
    public NewSubscriberResultMsg newSubscriber(
        @WebParam(name = "NewSubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "NewSubscriberRequestMsg")
        NewSubscriberRequestMsg newSubscriberRequestMsg);

    /**
     * 
     * @param reNewSubscriberRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ReNewSubscriberResultMsg
     */
    @WebMethod(operationName = "ReNewSubscriber", action = "ReNewSubscriber")
    @WebResult(name = "ReNewSubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ReNewSubscriberResultMsg")
    public ReNewSubscriberResultMsg reNewSubscriber(
        @WebParam(name = "ReNewSubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ReNewSubscriberRequestMsg")
        ReNewSubscriberRequestMsg reNewSubscriberRequestMsg);

    /**
     * 
     * @param deleteSubscriberRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.DeleteSubscriberResultMsg
     */
    @WebMethod(operationName = "DeleteSubscriber", action = "DeleteSubscriber")
    @WebResult(name = "DeleteSubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "DeleteSubscriberResultMsg")
    public DeleteSubscriberResultMsg deleteSubscriber(
        @WebParam(name = "DeleteSubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "DeleteSubscriberRequestMsg")
        DeleteSubscriberRequestMsg deleteSubscriberRequestMsg);

    /**
     * 
     * @param changeMainProdRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeMainProdResultMsg
     */
    @WebMethod(operationName = "ChangeMainProd", action = "ChangeMainProd")
    @WebResult(name = "ChangeMainProdResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeMainProdResultMsg")
    public ChangeMainProdResultMsg changeMainProd(
        @WebParam(name = "ChangeMainProdRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeMainProdRequestMsg")
        ChangeMainProdRequestMsg changeMainProdRequestMsg);

    /**
     * 
     * @param subscribeAppendantProductRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.SubscribeAppendantProductResultMsg
     */
    @WebMethod(operationName = "SubscribeAppendantProduct", action = "SubscribeAppendantProduct")
    @WebResult(name = "SubscribeAppendantProductResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "SubscribeAppendantProductResultMsg")
    public SubscribeAppendantProductResultMsg subscribeAppendantProduct(
        @WebParam(name = "SubscribeAppendantProductRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "SubscribeAppendantProductRequestMsg")
        SubscribeAppendantProductRequestMsg subscribeAppendantProductRequestMsg);

    /**
     * 
     * @param changeAppendantProductRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeAppendantProductResultMsg
     */
    @WebMethod(operationName = "ChangeAppendantProduct", action = "ChangeAppendantProduct")
    @WebResult(name = "ChangeAppendantProductResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeAppendantProductResultMsg")
    public ChangeAppendantProductResultMsg changeAppendantProduct(
        @WebParam(name = "ChangeAppendantProductRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeAppendantProductRequestMsg")
        ChangeAppendantProductRequestMsg changeAppendantProductRequestMsg);

    /**
     * 
     * @param unSubscribeAppendantProductRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.UnSubscribeAppendantProductResultMsg
     */
    @WebMethod(operationName = "UnSubscribeAppendantProduct", action = "UnSubscribeAppendantProduct")
    @WebResult(name = "UnSubscribeAppendantProductResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "UnSubscribeAppendantProductResultMsg")
    public UnSubscribeAppendantProductResultMsg unSubscribeAppendantProduct(
        @WebParam(name = "UnSubscribeAppendantProductRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "UnSubscribeAppendantProductRequestMsg")
        UnSubscribeAppendantProductRequestMsg unSubscribeAppendantProductRequestMsg);

    /**
     * 
     * @param changeCustBasicInforRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeCustBasicInforResultMsg
     */
    @WebMethod(operationName = "ChangeCustBasicInfor", action = "ChangeCustBasicInfor")
    @WebResult(name = "ChangeCustBasicInforResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeCustBasicInforResultMsg")
    public ChangeCustBasicInforResultMsg changeCustBasicInfor(
        @WebParam(name = "ChangeCustBasicInforRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeCustBasicInforRequestMsg")
        ChangeCustBasicInforRequestMsg changeCustBasicInforRequestMsg);

    /**
     * 
     * @param changeSubscriberBasicInforRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeSubscriberBasicInforResultMsg
     */
    @WebMethod(operationName = "ChangeSubscriberBasicInfor", action = "ChangeSubscriberBasicInfor")
    @WebResult(name = "ChangeSubscriberBasicInforResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeSubscriberBasicInforResultMsg")
    public ChangeSubscriberBasicInforResultMsg changeSubscriberBasicInfor(
        @WebParam(name = "ChangeSubscriberBasicInforRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeSubscriberBasicInforRequestMsg")
        ChangeSubscriberBasicInforRequestMsg changeSubscriberBasicInforRequestMsg);

    /**
     * 
     * @param changeAccountBasicInforRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeAccountBasicInforResultMsg
     */
    @WebMethod(operationName = "ChangeAccountBasicInfor", action = "ChangeAccountBasicInfor")
    @WebResult(name = "ChangeAccountBasicInforResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeAccountBasicInforResultMsg")
    public ChangeAccountBasicInforResultMsg changeAccountBasicInfor(
        @WebParam(name = "ChangeAccountBasicInforRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeAccountBasicInforRequestMsg")
        ChangeAccountBasicInforRequestMsg changeAccountBasicInforRequestMsg);

    /**
     * 
     * @param changePasswordRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangePasswordResultMsg
     */
    @WebMethod(operationName = "ChangePassword", action = "ChangePassword")
    @WebResult(name = "ChangePasswordResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangePasswordResultMsg")
    public ChangePasswordResultMsg changePassword(
        @WebParam(name = "ChangePasswordRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangePasswordRequestMsg")
        ChangePasswordRequestMsg changePasswordRequestMsg);

    /**
     * 
     * @param resetPasswordRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ResetPasswordResultMsg
     */
    @WebMethod(operationName = "ResetPassword", action = "ResetPassword")
    @WebResult(name = "ResetPasswordResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ResetPasswordResultMsg")
    public ResetPasswordResultMsg resetPassword(
        @WebParam(name = "ResetPasswordRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ResetPasswordRequestMsg")
        ResetPasswordRequestMsg resetPasswordRequestMsg);

    /**
     * 
     * @param changeMSISDNRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeMSISDNResultMsg
     */
    @WebMethod(operationName = "ChangeMSISDN", action = "ChangeMSISDN")
    @WebResult(name = "ChangeMSISDNResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeMSISDNResultMsg")
    public ChangeMSISDNResultMsg changeMSISDN(
        @WebParam(name = "ChangeMSISDNRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeMSISDNRequestMsg")
        ChangeMSISDNRequestMsg changeMSISDNRequestMsg);

    /**
     * 
     * @param changeSIMRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeSIMResultMsg
     */
    @WebMethod(operationName = "ChangeSIM", action = "ChangeSIM")
    @WebResult(name = "ChangeSIMResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeSIMResultMsg")
    public ChangeSIMResultMsg changeSIM(
        @WebParam(name = "ChangeSIMRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeSIMRequestMsg")
        ChangeSIMRequestMsg changeSIMRequestMsg);

    /**
     * 
     * @param syncDDSRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.SyncDDSResultMsg
     */
    @WebMethod(operationName = "SyncDDS", action = "SyncDDS")
    @WebResult(name = "SyncDDSResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "SyncDDSResultMsg")
    public SyncDDSResultMsg syncDDS(
        @WebParam(name = "SyncDDSRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "SyncDDSRequestMsg")
        SyncDDSRequestMsg syncDDSRequestMsg);

    /**
     * 
     * @param changeServicesRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeServicesResultMsg
     */
    @WebMethod(operationName = "ChangeServices", action = "ChangeServices")
    @WebResult(name = "ChangeServicesResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeServicesResultMsg")
    public ChangeServicesResultMsg changeServices(
        @WebParam(name = "ChangeServicesRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeServicesRequestMsg")
        ChangeServicesRequestMsg changeServicesRequestMsg);

    /**
     * 
     * @param deleteRechageBlackRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.DeleteRechageBlackResultMsg
     */
    @WebMethod(operationName = "DeleteRechageBlack", action = "DeleteRechageBlack")
    @WebResult(name = "DeleteRechageBlackResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "DeleteRechageBlackResultMsg")
    public DeleteRechageBlackResultMsg deleteRechageBlack(
        @WebParam(name = "DeleteRechageBlackRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "DeleteRechageBlackRequestMsg")
        DeleteRechageBlackRequestMsg deleteRechageBlackRequestMsg);

    /**
     * 
     * @param suspendRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.SuspendResultMsg
     */
    @WebMethod(operationName = "Suspend", action = "Suspend")
    @WebResult(name = "SuspendResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "SuspendResultMsg")
    public SuspendResultMsg suspend(
        @WebParam(name = "SuspendRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "SuspendRequestMsg")
        SuspendRequestMsg suspendRequestMsg);

    /**
     * 
     * @param reconnectRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ReconnectResultMsg
     */
    @WebMethod(operationName = "Reconnect", action = "Reconnect")
    @WebResult(name = "ReconnectResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ReconnectResultMsg")
    public ReconnectResultMsg reconnect(
        @WebParam(name = "ReconnectRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ReconnectRequestMsg")
        ReconnectRequestMsg reconnectRequestMsg);

    /**
     * 
     * @param claimMissingRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ClaimMissingResultMsg
     */
    @WebMethod(operationName = "ClaimMissing", action = "ClaimMissing")
    @WebResult(name = "ClaimMissingResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ClaimMissingResultMsg")
    public ClaimMissingResultMsg claimMissing(
        @WebParam(name = "ClaimMissingRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ClaimMissingRequestMsg")
        ClaimMissingRequestMsg claimMissingRequestMsg);

    /**
     * 
     * @param disclaimMissingRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.DisclaimMissingResultMsg
     */
    @WebMethod(operationName = "DisclaimMissing", action = "DisclaimMissing")
    @WebResult(name = "DisclaimMissingResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "DisclaimMissingResultMsg")
    public DisclaimMissingResultMsg disclaimMissing(
        @WebParam(name = "DisclaimMissingRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "DisclaimMissingRequestMsg")
        DisclaimMissingRequestMsg disclaimMissingRequestMsg);

    /**
     * 
     * @param batchOperationRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.BatchOperationResultMsg
     */
    @WebMethod(operationName = "BatchOperation", action = "BatchOperation")
    @WebResult(name = "BatchOperationResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "BatchOperationResultMsg")
    public BatchOperationResultMsg batchOperation(
        @WebParam(name = "BatchOperationRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "BatchOperationRequestMsg")
        BatchOperationRequestMsg batchOperationRequestMsg);

    /**
     * 
     * @param changeOwnerRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeOwnerResultMsg
     */
    @WebMethod(operationName = "ChangeOwner", action = "ChangeOwner")
    @WebResult(name = "ChangeOwnerResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeOwnerResultMsg")
    public ChangeOwnerResultMsg changeOwner(
        @WebParam(name = "ChangeOwnerRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeOwnerRequestMsg")
        ChangeOwnerRequestMsg changeOwnerRequestMsg);

    /**
     * 
     * @param queryUserGroupRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryUserGroupResultMsg
     */
    @WebMethod(operationName = "QueryUserGroup", action = "QueryUserGroup")
    @WebResult(name = "QueryUserGroupResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryUserGroupResultMsg")
    public QueryUserGroupResultMsg queryUserGroup(
        @WebParam(name = "QueryUserGroupRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryUserGroupRequestMsg")
        QueryUserGroupRequestMsg queryUserGroupRequestMsg);

    /**
     * 
     * @param manGroupMemberRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManGroupMemberResultMsg
     */
    @WebMethod(operationName = "ManGroupMember", action = "ManGroupMember")
    @WebResult(name = "ManGroupMemberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManGroupMemberResultMsg")
    public ManGroupMemberResultMsg manGroupMember(
        @WebParam(name = "ManGroupMemberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManGroupMemberRequestMsg")
        ManGroupMemberRequestMsg manGroupMemberRequestMsg);

    /**
     * 
     * @param querySubscribedGroupRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QuerySubscribedGroupResultMsg
     */
    @WebMethod(operationName = "QuerySubscribedGroup", action = "QuerySubscribedGroup")
    @WebResult(name = "QuerySubscribedGroupResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubscribedGroupResultMsg")
    public QuerySubscribedGroupResultMsg querySubscribedGroup(
        @WebParam(name = "QuerySubscribedGroupRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubscribedGroupRequestMsg")
        QuerySubscribedGroupRequestMsg querySubscribedGroupRequestMsg);

    /**
     * 
     * @param modifySubscriberValidityRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ModifySubscriberValidityResultMsg
     */
    @WebMethod(operationName = "ModifySubscriberValidity", action = "ModifySubscriberValidity")
    @WebResult(name = "ModifySubscriberValidityResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifySubscriberValidityResultMsg")
    public ModifySubscriberValidityResultMsg modifySubscriberValidity(
        @WebParam(name = "ModifySubscriberValidityRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifySubscriberValidityRequestMsg")
        ModifySubscriberValidityRequestMsg modifySubscriberValidityRequestMsg);

    /**
     * 
     * @param integrationEnquiryRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.IntegrationEnquiryResultMsg
     */
    @WebMethod(operationName = "IntegrationEnquiry", action = "IntegrationEnquiry")
    @WebResult(name = "IntegrationEnquiryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "IntegrationEnquiryResultMsg")
    public IntegrationEnquiryResultMsg integrationEnquiry(
        @WebParam(name = "IntegrationEnquiryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "IntegrationEnquiryRequestMsg")
        IntegrationEnquiryRequestMsg integrationEnquiryRequestMsg);

    /**
     * 
     * @param querySubscriberProductInfoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QuerySubscriberProductInfoResultMsg
     */
    @WebMethod(operationName = "QuerySubscriberProductInfo", action = "QuerySubscriberProductInfo")
    @WebResult(name = "QuerySubscriberProductInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubscriberProductInfoResultMsg")
    public QuerySubscriberProductInfoResultMsg querySubscriberProductInfo(
        @WebParam(name = "QuerySubscriberProductInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubscriberProductInfoRequestMsg")
        QuerySubscriberProductInfoRequestMsg querySubscriberProductInfoRequestMsg);

    /**
     * 
     * @param querySubscriberServiceInfoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QuerySubscriberServiceInfoResultMsg
     */
    @WebMethod(operationName = "QuerySubscriberServiceInfo", action = "QuerySubscriberServiceInfo")
    @WebResult(name = "QuerySubscriberServiceInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubscriberServiceInfoResultMsg")
    public QuerySubscriberServiceInfoResultMsg querySubscriberServiceInfo(
        @WebParam(name = "QuerySubscriberServiceInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubscriberServiceInfoRequestMsg")
        QuerySubscriberServiceInfoRequestMsg querySubscriberServiceInfoRequestMsg);

    /**
     * 
     * @param modifySubscriberStateRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ModifySubscriberStateResultMsg
     */
    @WebMethod(operationName = "ModifySubscriberState", action = "ModifySubscriberState")
    @WebResult(name = "ModifySubscriberStateResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifySubscriberStateResultMsg")
    public ModifySubscriberStateResultMsg modifySubscriberState(
        @WebParam(name = "ModifySubscriberStateRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifySubscriberStateRequestMsg")
        ModifySubscriberStateRequestMsg modifySubscriberStateRequestMsg);

    /**
     * 
     * @param modifySubscriberEmoticonRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ModifySubscriberEmoticonResultMsg
     */
    @WebMethod(operationName = "ModifySubscriberEmoticon", action = "ModifySubscriberEmoticon")
    @WebResult(name = "ModifySubscriberEmoticonResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifySubscriberEmoticonResultMsg")
    public ModifySubscriberEmoticonResultMsg modifySubscriberEmoticon(
        @WebParam(name = "ModifySubscriberEmoticonRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifySubscriberEmoticonRequestMsg")
        ModifySubscriberEmoticonRequestMsg modifySubscriberEmoticonRequestMsg);

    /**
     * 
     * @param manSubCallScreenNoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManSubCallScreenNoResultMsg
     */
    @WebMethod(operationName = "ManSubCallScreenNo", action = "ManSubCallScreenNo")
    @WebResult(name = "ManSubCallScreenNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManSubCallScreenNoResultMsg")
    public ManSubCallScreenNoResultMsg manSubCallScreenNo(
        @WebParam(name = "ManSubCallScreenNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManSubCallScreenNoRequestMsg")
        ManSubCallScreenNoRequestMsg manSubCallScreenNoRequestMsg);

    /**
     * 
     * @param manSubFamilyNoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManSubFamilyNoResultMsg
     */
    @WebMethod(operationName = "ManSubFamilyNo", action = "ManSubFamilyNo")
    @WebResult(name = "ManSubFamilyNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManSubFamilyNoResultMsg")
    public ManSubFamilyNoResultMsg manSubFamilyNo(
        @WebParam(name = "ManSubFamilyNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManSubFamilyNoRequestMsg")
        ManSubFamilyNoRequestMsg manSubFamilyNoRequestMsg);

    /**
     * 
     * @param changeSubLowBalPrtRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeSubLowBalPrtResultMsg
     */
    @WebMethod(operationName = "ChangeSubLowBalPrt", action = "ChangeSubLowBalPrt")
    @WebResult(name = "ChangeSubLowBalPrtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeSubLowBalPrtResultMsg")
    public ChangeSubLowBalPrtResultMsg changeSubLowBalPrt(
        @WebParam(name = "ChangeSubLowBalPrtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeSubLowBalPrtRequestMsg")
        ChangeSubLowBalPrtRequestMsg changeSubLowBalPrtRequestMsg);

    /**
     * 
     * @param querySubLowBalPrtRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QuerySubLowBalPrtResultMsg
     */
    @WebMethod(operationName = "QuerySubLowBalPrt", action = "QuerySubLowBalPrt")
    @WebResult(name = "QuerySubLowBalPrtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubLowBalPrtResultMsg")
    public QuerySubLowBalPrtResultMsg querySubLowBalPrt(
        @WebParam(name = "QuerySubLowBalPrtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubLowBalPrtRequestMsg")
        QuerySubLowBalPrtRequestMsg querySubLowBalPrtRequestMsg);

    /**
     * 
     * @param manSubHomeZoneRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManSubHomeZoneResultMsg
     */
    @WebMethod(operationName = "ManSubHomeZone", action = "ManSubHomeZone")
    @WebResult(name = "ManSubHomeZoneResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManSubHomeZoneResultMsg")
    public ManSubHomeZoneResultMsg manSubHomeZone(
        @WebParam(name = "ManSubHomeZoneRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManSubHomeZoneRequestMsg")
        ManSubHomeZoneRequestMsg manSubHomeZoneRequestMsg);

    /**
     * 
     * @param modifyPosUserStateRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ModifyPosUserStateResultMsg
     */
    @WebMethod(operationName = "ModifyPosUserState", action = "ModifyPosUserState")
    @WebResult(name = "ModifyPosUserStateResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifyPosUserStateResultMsg")
    public ModifyPosUserStateResultMsg modifyPosUserState(
        @WebParam(name = "ModifyPosUserStateRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifyPosUserStateRequestMsg")
        ModifyPosUserStateRequestMsg modifyPosUserStateRequestMsg);

    /**
     * 
     * @param queryAdjustValidityLogRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryAdjustValidityLogResultMsg
     */
    @WebMethod(operationName = "QueryAdjustValidityLog", action = "QueryAdjustValidityLog")
    @WebResult(name = "QueryAdjustValidityLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryAdjustValidityLogResultMsg")
    public QueryAdjustValidityLogResultMsg queryAdjustValidityLog(
        @WebParam(name = "QueryAdjustValidityLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryAdjustValidityLogRequestMsg")
        QueryAdjustValidityLogRequestMsg queryAdjustValidityLogRequestMsg);

    /**
     * 
     * @param querySubFamilyNoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QuerySubFamilyNoResultMsg
     */
    @WebMethod(operationName = "QuerySubFamilyNo", action = "QuerySubFamilyNo")
    @WebResult(name = "QuerySubFamilyNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubFamilyNoResultMsg")
    public QuerySubFamilyNoResultMsg querySubFamilyNo(
        @WebParam(name = "QuerySubFamilyNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubFamilyNoRequestMsg")
        QuerySubFamilyNoRequestMsg querySubFamilyNoRequestMsg);

    /**
     * 
     * @param querySubHomeZoneRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QuerySubHomeZoneResultMsg
     */
    @WebMethod(operationName = "QuerySubHomeZone", action = "QuerySubHomeZone")
    @WebResult(name = "QuerySubHomeZoneResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubHomeZoneResultMsg")
    public QuerySubHomeZoneResultMsg querySubHomeZone(
        @WebParam(name = "QuerySubHomeZoneRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubHomeZoneRequestMsg")
        QuerySubHomeZoneRequestMsg querySubHomeZoneRequestMsg);

    /**
     * 
     * @param querySubCallScreenNoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QuerySubCallScreenNoResultMsg
     */
    @WebMethod(operationName = "QuerySubCallScreenNo", action = "QuerySubCallScreenNo")
    @WebResult(name = "QuerySubCallScreenNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubCallScreenNoResultMsg")
    public QuerySubCallScreenNoResultMsg querySubCallScreenNo(
        @WebParam(name = "QuerySubCallScreenNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubCallScreenNoRequestMsg")
        QuerySubCallScreenNoRequestMsg querySubCallScreenNoRequestMsg);

    /**
     * 
     * @param queryGroupMemberRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryGroupMemberResultMsg
     */
    @WebMethod(operationName = "QueryGroupMember", action = "QueryGroupMember")
    @WebResult(name = "QueryGroupMemberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryGroupMemberResultMsg")
    public QueryGroupMemberResultMsg queryGroupMember(
        @WebParam(name = "QueryGroupMemberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryGroupMemberRequestMsg")
        QueryGroupMemberRequestMsg queryGroupMemberRequestMsg);

    /**
     * 
     * @param querySubChangeLogRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QuerySubChangeLogResultMsg
     */
    @WebMethod(operationName = "QuerySubChangeLog", action = "QuerySubChangeLog")
    @WebResult(name = "QuerySubChangeLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubChangeLogResultMsg")
    public QuerySubChangeLogResultMsg querySubChangeLog(
        @WebParam(name = "QuerySubChangeLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QuerySubChangeLogRequestMsg")
        QuerySubChangeLogRequestMsg querySubChangeLogRequestMsg);

    /**
     * 
     * @param manParentChildRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManParentChildResultMsg
     */
    @WebMethod(operationName = "ManParentChild", action = "ManParentChild")
    @WebResult(name = "ManParentChildResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManParentChildResultMsg")
    public ManParentChildResultMsg manParentChild(
        @WebParam(name = "ManParentChildRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManParentChildRequestMsg")
        ManParentChildRequestMsg manParentChildRequestMsg);

    /**
     * 
     * @param queryChildLimitRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryChildLimitResultMsg
     */
    @WebMethod(operationName = "QueryChildLimit", action = "QueryChildLimit")
    @WebResult(name = "QueryChildLimitResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryChildLimitResultMsg")
    public QueryChildLimitResultMsg queryChildLimit(
        @WebParam(name = "QueryChildLimitRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryChildLimitRequestMsg")
        QueryChildLimitRequestMsg queryChildLimitRequestMsg);

    /**
     * 
     * @param modifyCFNoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ModifyCFNoResultMsg
     */
    @WebMethod(operationName = "ModifyCFNo", action = "ModifyCFNo")
    @WebResult(name = "ModifyCFNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifyCFNoResultMsg")
    public ModifyCFNoResultMsg modifyCFNo(
        @WebParam(name = "ModifyCFNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ModifyCFNoRequestMsg")
        ModifyCFNoRequestMsg modifyCFNoRequestMsg);

    /**
     * 
     * @param blockSubscriberRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.BlockSubscriberResultMsg
     */
    @WebMethod(operationName = "BlockSubscriber", action = "BlockSubscriber")
    @WebResult(name = "BlockSubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "BlockSubscriberResultMsg")
    public BlockSubscriberResultMsg blockSubscriber(
        @WebParam(name = "BlockSubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "BlockSubscriberRequestMsg")
        BlockSubscriberRequestMsg blockSubscriberRequestMsg);

    /**
     * 
     * @param newSubscriberExtRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.NewSubscriberExtResultMsg
     */
    @WebMethod(operationName = "NewSubscriberExt", action = "NewSubscriberExt")
    @WebResult(name = "NewSubscriberExtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "NewSubscriberExtResultMsg")
    public NewSubscriberExtResultMsg newSubscriberExt(
        @WebParam(name = "NewSubscriberExtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "NewSubscriberExtRequestMsg")
        NewSubscriberExtRequestMsg newSubscriberExtRequestMsg);

    /**
     * 
     * @param bindProductSubscriberNoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.BindProductSubscriberNoResultMsg
     */
    @WebMethod(operationName = "BindProductSubscriberNo", action = "BindProductSubscriberNo")
    @WebResult(name = "BindProductSubscriberNoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "BindProductSubscriberNoResultMsg")
    public BindProductSubscriberNoResultMsg bindProductSubscriberNo(
        @WebParam(name = "BindProductSubscriberNoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "BindProductSubscriberNoRequestMsg")
        BindProductSubscriberNoRequestMsg bindProductSubscriberNoRequestMsg);

    /**
     * 
     * @param deleteSubscriberExtRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.DeleteSubscriberExtResultMsg
     */
    @WebMethod(operationName = "DeleteSubscriberExt", action = "DeleteSubscriberExt")
    @WebResult(name = "DeleteSubscriberExtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "DeleteSubscriberExtResultMsg")
    public DeleteSubscriberExtResultMsg deleteSubscriberExt(
        @WebParam(name = "DeleteSubscriberExtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "DeleteSubscriberExtRequestMsg")
        DeleteSubscriberExtRequestMsg deleteSubscriberExtRequestMsg);

    /**
     * 
     * @param unSubscribeAppendantProductExtRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.UnSubscribeAppendantProductExtResultMsg
     */
    @WebMethod(operationName = "UnSubscribeAppendantProductExt", action = "UnSubscribeAppendantProductExt")
    @WebResult(name = "UnSubscribeAppendantProductExtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "UnSubscribeAppendantProductExtResultMsg")
    public UnSubscribeAppendantProductExtResultMsg unSubscribeAppendantProductExt(
        @WebParam(name = "UnSubscribeAppendantProductExtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "UnSubscribeAppendantProductExtRequestMsg")
        UnSubscribeAppendantProductExtRequestMsg unSubscribeAppendantProductExtRequestMsg);

    /**
     * 
     * @param queryDefinedZonesInfoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryDefinedZonesInfoResultMsg
     */
    @WebMethod(operationName = "QueryDefinedZonesInfo", action = "QueryDefinedZonesInfo")
    @WebResult(name = "QueryDefinedZonesInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryDefinedZonesInfoResultMsg")
    public QueryDefinedZonesInfoResultMsg queryDefinedZonesInfo(
        @WebParam(name = "QueryDefinedZonesInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryDefinedZonesInfoRequestMsg")
        QueryDefinedZonesInfoRequestMsg queryDefinedZonesInfoRequestMsg);

    /**
     * 
     * @param checkOperatorPasswordRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.CheckOperatorPasswordResultMsg
     */
    @WebMethod(operationName = "CheckOperatorPassword", action = "CheckOperatorPassword")
    @WebResult(name = "CheckOperatorPasswordResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "CheckOperatorPasswordResultMsg")
    public CheckOperatorPasswordResultMsg checkOperatorPassword(
        @WebParam(name = "CheckOperatorPasswordRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "CheckOperatorPasswordRequestMsg")
        CheckOperatorPasswordRequestMsg checkOperatorPasswordRequestMsg);

    /**
     * 
     * @param changeCreditLevelRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangeCreditLevelResultMsg
     */
    @WebMethod(operationName = "ChangeCreditLevel", action = "ChangeCreditLevel")
    @WebResult(name = "ChangeCreditLevelResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeCreditLevelResultMsg")
    public ChangeCreditLevelResultMsg changeCreditLevel(
        @WebParam(name = "ChangeCreditLevelRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangeCreditLevelRequestMsg")
        ChangeCreditLevelRequestMsg changeCreditLevelRequestMsg);

    /**
     * 
     * @param manageLoanSMSRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManageLoanSMSResultMsg
     */
    @WebMethod(operationName = "ManageLoanSMS", action = "ManageLoanSMS")
    @WebResult(name = "ManageLoanSMSResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManageLoanSMSResultMsg")
    public ManageLoanSMSResultMsg manageLoanSMS(
        @WebParam(name = "ManageLoanSMSRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManageLoanSMSRequestMsg")
        ManageLoanSMSRequestMsg manageLoanSMSRequestMsg);

    /**
     * 
     * @param queryLoanSMSRequest
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryLoanSMSResultMsg
     */
    @WebMethod(operationName = "QueryLoanSMS", action = "urn:#QueryLoanSMS")
    @WebResult(name = "QueryLoanSMSResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryLoanSMSResult")
    public QueryLoanSMSResultMsg queryLoanSMS(
        @WebParam(name = "QueryLoanSMSRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryLoanSMSRequest")
        QueryLoanSMSRequestMsg queryLoanSMSRequest);

    /**
     * 
     * @param extendMSFValidityRequest
     * @return
     *     returns com.huawei.ocs55.businessmgr.ExtendMSFValidityResultMsg
     */
    @WebMethod(operationName = "ExtendMSFValidity", action = "ExtendMSFValidity")
    @WebResult(name = "ExtendMSFValidityResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ExtendMSFValidityResult")
    public ExtendMSFValidityResultMsg extendMSFValidity(
        @WebParam(name = "ExtendMSFValidityRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ExtendMSFValidityRequest")
        ExtendMSFValidityRequestMsg extendMSFValidityRequest);

    /**
     * 
     * @param queryInterActLogRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryInterActLogResultMsg
     */
    @WebMethod(operationName = "QueryInterActLog", action = "QueryInterActLog")
    @WebResult(name = "QueryInterActLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryInterActLogResultMsg")
    public QueryInterActLogResultMsg queryInterActLog(
        @WebParam(name = "QueryInterActLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryInterActLogRequestMsg")
        QueryInterActLogRequestMsg queryInterActLogRequestMsg);

    /**
     * 
     * @param changePaymentPlanRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ChangePaymentPlanResultMsg
     */
    @WebMethod(operationName = "ChangePaymentPlan", action = "ChangePaymentPlan")
    @WebResult(name = "ChangePaymentPlanResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangePaymentPlanResultMsg")
    public ChangePaymentPlanResultMsg changePaymentPlan(
        @WebParam(name = "ChangePaymentPlanRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ChangePaymentPlanRequestMsg")
        ChangePaymentPlanRequestMsg changePaymentPlanRequestMsg);

    /**
     * 
     * @param manPairNumberRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManPairNumberResultMsg
     */
    @WebMethod(operationName = "ManPairNumber", action = "ManPairNumber")
    @WebResult(name = "ManPairNumberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManPairNumberResultMsg")
    public ManPairNumberResultMsg manPairNumber(
        @WebParam(name = "ManPairNumberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManPairNumberRequestMsg")
        ManPairNumberRequestMsg manPairNumberRequestMsg);

    /**
     * 
     * @param queryPairNumberRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryPairNumberResultMsg
     */
    @WebMethod(operationName = "QueryPairNumber", action = "QueryPairNumber")
    @WebResult(name = "QueryPairNumberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryPairNumberResultMsg")
    public QueryPairNumberResultMsg queryPairNumber(
        @WebParam(name = "QueryPairNumberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryPairNumberRequestMsg")
        QueryPairNumberRequestMsg queryPairNumberRequestMsg);

    /**
     * 
     * @param queryCUGMembersRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryCUGMembersResultMsg
     */
    @WebMethod(operationName = "QueryCUGMembers", action = "QueryCUGMembers")
    @WebResult(name = "QueryCUGMembersResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryCUGMembersResultMsg")
    public QueryCUGMembersResultMsg queryCUGMembers(
        @WebParam(name = "QueryCUGMembersRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryCUGMembersRequestMsg")
        QueryCUGMembersRequestMsg queryCUGMembersRequestMsg);

    /**
     * 
     * @param manageMemberOfGroupCugRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManageMemberOfGroupCugResultMsg
     */
    @WebMethod(operationName = "ManageMemberOfGroupCug", action = "ManageMemberOfGroupCug")
    @WebResult(name = "ManageMemberOfGroupCugResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManageMemberOfGroupCugResultMsg")
    public ManageMemberOfGroupCugResultMsg manageMemberOfGroupCug(
        @WebParam(name = "ManageMemberOfGroupCugRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManageMemberOfGroupCugRequestMsg")
        ManageMemberOfGroupCugRequestMsg manageMemberOfGroupCugRequestMsg);

    /**
     * 
     * @param manCUGInfoRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManCUGInfoResultMsg
     */
    @WebMethod(operationName = "ManCUGInfo", action = "ManCUGInfo")
    @WebResult(name = "ManCUGInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManCUGInfoResultMsg")
    public ManCUGInfoResultMsg manCUGInfo(
        @WebParam(name = "ManCUGInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManCUGInfoRequestMsg")
        ManCUGInfoRequestMsg manCUGInfoRequestMsg);

    /**
     * 
     * @param manPromotionPlanRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.ManPromotionPlanResultMsg
     */
    @WebMethod(operationName = "ManPromotionPlan", action = "ManPromotionPlan")
    @WebResult(name = "ManPromotionPlanResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManPromotionPlanResultMsg")
    public ManPromotionPlanResultMsg manPromotionPlan(
        @WebParam(name = "ManPromotionPlanRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "ManPromotionPlanRequestMsg")
        ManPromotionPlanRequestMsg manPromotionPlanRequestMsg);

    /**
     * 
     * @param queryPromotionPlanRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryPromotionPlanResultMsg
     */
    @WebMethod(operationName = "QueryPromotionPlan", action = "QueryPromotionPlan")
    @WebResult(name = "QueryPromotionPlanResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryPromotionPlanResultMsg")
    public QueryPromotionPlanResultMsg queryPromotionPlan(
        @WebParam(name = "QueryPromotionPlanRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "QueryPromotionPlanRequestMsg")
        QueryPromotionPlanRequestMsg queryPromotionPlanRequestMsg);

    /**
     * 
     * @param updateCUGListRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.UpdateCUGListResultMsg
     */
    @WebMethod(operationName = "UpdateCUGList", action = "UpdateCUGList")
    @WebResult(name = "UpdateCUGListResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "UpdateCUGListResultMsg")
    public UpdateCUGListResultMsg updateCUGList(
        @WebParam(name = "UpdateCUGListRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "UpdateCUGListRequestMsg")
        UpdateCUGListRequestMsg updateCUGListRequestMsg);

    /**
     * 
     * @param setDTNotificationRequestMsg
     * @return
     *     returns com.huawei.ocs55.businessmgr.SetDTNotificationResultMsg
     */
    @WebMethod(operationName = "SetDTNotification", action = "SetDTNotification")
    @WebResult(name = "SetDTNotificationResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "SetDTNotificationResultMsg")
    public SetDTNotificationResultMsg setDTNotification(
        @WebParam(name = "SetDTNotificationRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "SetDTNotificationRequestMsg")
        SetDTNotificationRequestMsg setDTNotificationRequestMsg);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs55.businessmgr.QueryBillingByDateExtResultMsg
     */
    @WebMethod(operationName = "QueryBillingByDateExt", action = "QueryBillingByDateExt")
    @WebResult(name = "QueryBillingByDateExtResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
    public QueryBillingByDateExtResultMsg queryBillingByDateExt(
        @WebParam(name = "QueryBillingByDateExtRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/businessmgrmsg", partName = "part1")
        QueryBillingByDateExtRequestMsg part1);

}
