
package com.huawei.ocs55.arservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ArServices", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ArServices {


    /**
     * 
     * @param transferBalanceRequestMsg
     * @return
     *     returns com.huawei.ocs55.arservices.TransferBalanceResultMsg
     */
    @WebMethod(operationName = "TransferBalance", action = "TransferBalance")
    @WebResult(name = "TransferBalanceResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "TransferBalanceResultMsg")
    public TransferBalanceResultMsg transferBalance(
        @WebParam(name = "TransferBalanceRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "TransferBalanceRequestMsg")
        TransferBalanceRequestMsg transferBalanceRequestMsg);

    /**
     * 
     * @param adjustmentRequestMsg
     * @return
     *     returns com.huawei.ocs55.arservices.AdjustmentResultMsg
     */
    @WebMethod(operationName = "Adjustment", action = "Adjustment")
    @WebResult(name = "AdjustmentResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "AdjustmentResultMsg")
    public AdjustmentResultMsg adjustment(
        @WebParam(name = "AdjustmentRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "AdjustmentRequestMsg")
        AdjustmentRequestMsg adjustmentRequestMsg);

    /**
     * 
     * @param loanRequestMsg
     * @return
     *     returns com.huawei.ocs55.arservices.LoanResultMsg
     */
    @WebMethod(operationName = "Loan", action = "Loan")
    @WebResult(name = "LoanResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "LoanResultMsg")
    public LoanResultMsg loan(
        @WebParam(name = "LoanRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "LoanRequestMsg")
        LoanRequestMsg loanRequestMsg);

    /**
     * 
     * @param queryLoanLogRequestMsg
     * @return
     *     returns com.huawei.ocs55.arservices.QueryLoanLogResultMsg
     */
    @WebMethod(operationName = "QueryLoanLog", action = "QueryLoanLog")
    @WebResult(name = "QueryLoanLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "QueryLoanLogResultMsg")
    public QueryLoanLogResultMsg queryLoanLog(
        @WebParam(name = "QueryLoanLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "QueryLoanLogRequestMsg")
        QueryLoanLogRequestMsg queryLoanLogRequestMsg);

    /**
     * 
     * @param queryOCSBalanceRequestMsg
     * @return
     *     returns com.huawei.ocs55.arservices.QueryOCSBalanceResultMsg
     */
    @WebMethod(operationName = "QueryOCSBalance", action = "QueryOCSBalance")
    @WebResult(name = "QueryOCSBalanceResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "QueryOCSBalanceResultMsg")
    public QueryOCSBalanceResultMsg queryOCSBalance(
        @WebParam(name = "QueryOCSBalanceRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/arservices", partName = "QueryOCSBalanceRequestMsg")
        QueryOCSBalanceRequestMsg queryOCSBalanceRequestMsg);

}
