
package com.huawei.ocs55.acctmgr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CBSInterfaceAccountMgr", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CBSInterfaceAccountMgr {


    /**
     * 
     * @param queryBalanceRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.QueryBalanceResultMsg
     */
    @WebMethod(operationName = "QueryBalance", action = "QueryBalance")
    @WebResult(name = "QueryBalanceResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "QueryBalanceResultMsg")
    public QueryBalanceResultMsg queryBalance(
        @WebParam(name = "QueryBalanceRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "QueryBalanceRequestMsg")
        QueryBalanceRequestMsg queryBalanceRequestMsg);

    /**
     * 
     * @param voucherRechargeRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.VoucherRechargeResultMsg
     */
    @WebMethod(operationName = "VoucherRecharge", action = "VoucherRecharge")
    @WebResult(name = "VoucherRechargeResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherRechargeResultMsg")
    public VoucherRechargeResultMsg voucherRecharge(
        @WebParam(name = "VoucherRechargeRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherRechargeRequestMsg")
        VoucherRechargeRequestMsg voucherRechargeRequestMsg);

    /**
     * 
     * @param paymentRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.PaymentResultMsg
     */
    @WebMethod(operationName = "Payment", action = "Payment")
    @WebResult(name = "PaymentResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "PaymentResultMsg")
    public PaymentResultMsg payment(
        @WebParam(name = "PaymentRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "PaymentRequestMsg")
        PaymentRequestMsg paymentRequestMsg);

    /**
     * 
     * @param activeFirstRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.ActiveFirstResultMsg
     */
    @WebMethod(operationName = "ActiveFirst", action = "ActiveFirst")
    @WebResult(name = "ActiveFirstResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ActiveFirstResultMsg")
    public ActiveFirstResultMsg activeFirst(
        @WebParam(name = "ActiveFirstRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ActiveFirstRequestMsg")
        ActiveFirstRequestMsg activeFirstRequestMsg);

    /**
     * 
     * @param reversePaymentRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.ReversePaymentResultMsg
     */
    @WebMethod(operationName = "ReversePayment", action = "ReversePayment")
    @WebResult(name = "ReversePaymentResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ReversePaymentResultMsg")
    public ReversePaymentResultMsg reversePayment(
        @WebParam(name = "ReversePaymentRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ReversePaymentRequestMsg")
        ReversePaymentRequestMsg reversePaymentRequestMsg);

    /**
     * 
     * @param adjustAccountRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.AdjustAccountResultMsg
     */
    @WebMethod(operationName = "AdjustAccount", action = "AdjustAccount")
    @WebResult(name = "AdjustAccountResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "AdjustAccountResultMsg")
    public AdjustAccountResultMsg adjustAccount(
        @WebParam(name = "AdjustAccountRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "AdjustAccountRequestMsg")
        AdjustAccountRequestMsg adjustAccountRequestMsg);

    /**
     * 
     * @param voucherRechargeEnquiryRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.VoucherRechargeEnquiryResultMsg
     */
    @WebMethod(operationName = "VoucherRechargeEnquiry", action = "VoucherRechargeEnquiry")
    @WebResult(name = "VoucherRechargeEnquiryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherRechargeEnquiryResultMsg")
    public VoucherRechargeEnquiryResultMsg voucherRechargeEnquiry(
        @WebParam(name = "VoucherRechargeEnquiryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherRechargeEnquiryRequestMsg")
        VoucherRechargeEnquiryRequestMsg voucherRechargeEnquiryRequestMsg);

    /**
     * 
     * @param transferAccountRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.TransferAccountResultMsg
     */
    @WebMethod(operationName = "TransferAccount", action = "TransferAccount")
    @WebResult(name = "TransferAccountResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "TransferAccountResultMsg")
    public TransferAccountResultMsg transferAccount(
        @WebParam(name = "TransferAccountRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "TransferAccountRequestMsg")
        TransferAccountRequestMsg transferAccountRequestMsg);

    /**
     * 
     * @param paymentEnquiryRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.PaymentEnquiryResultMsg
     */
    @WebMethod(operationName = "PaymentEnquiry", action = "PaymentEnquiry")
    @WebResult(name = "PaymentEnquiryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "PaymentEnquiryResultMsg")
    public PaymentEnquiryResultMsg paymentEnquiry(
        @WebParam(name = "PaymentEnquiryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "PaymentEnquiryRequestMsg")
        PaymentEnquiryRequestMsg paymentEnquiryRequestMsg);

    /**
     * 
     * @param cumulateEnquiryRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.CumulateEnquiryResultMsg
     */
    @WebMethod(operationName = "CumulateEnquiry", action = "CumulateEnquiry")
    @WebResult(name = "CumulateEnquiryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "CumulateEnquiryResultMsg")
    public CumulateEnquiryResultMsg cumulateEnquiry(
        @WebParam(name = "CumulateEnquiryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "CumulateEnquiryRequestMsg")
        CumulateEnquiryRequestMsg cumulateEnquiryRequestMsg);

    /**
     * 
     * @param voucherEnquiryBySeqRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.VoucherEnquiryBySeqResultMsg
     */
    @WebMethod(operationName = "VoucherEnquiryBySeq", action = "VoucherEnquiryBySeq")
    @WebResult(name = "VoucherEnquiryBySeqResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherEnquiryBySeqResultMsg")
    public VoucherEnquiryBySeqResultMsg voucherEnquiryBySeq(
        @WebParam(name = "VoucherEnquiryBySeqRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherEnquiryBySeqRequestMsg")
        VoucherEnquiryBySeqRequestMsg voucherEnquiryBySeqRequestMsg);

    /**
     * 
     * @param voucherEnquiryByPINRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.VoucherEnquiryByPINResultMsg
     */
    @WebMethod(operationName = "VoucherEnquiryByPIN", action = "VoucherEnquiryByPIN")
    @WebResult(name = "VoucherEnquiryByPINResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherEnquiryByPINResultMsg")
    public VoucherEnquiryByPINResultMsg voucherEnquiryByPIN(
        @WebParam(name = "VoucherEnquiryByPINRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherEnquiryByPINRequestMsg")
        VoucherEnquiryByPINRequestMsg voucherEnquiryByPINRequestMsg);

    /**
     * 
     * @param oneOffDeductionRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.OneOffDeductionResultMsg
     */
    @WebMethod(operationName = "OneOffDeduction", action = "OneOffDeduction")
    @WebResult(name = "OneOffDeductionResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "OneOffDeductionResultMsg")
    public OneOffDeductionResultMsg oneOffDeduction(
        @WebParam(name = "OneOffDeductionRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "OneOffDeductionRequestMsg")
        OneOffDeductionRequestMsg oneOffDeductionRequestMsg);

    /**
     * 
     * @param serviceHandleFeeRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.ServiceHandleFeeResultMsg
     */
    @WebMethod(operationName = "ServiceHandleFee", action = "ServiceHandleFee")
    @WebResult(name = "ServiceHandleFeeResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ServiceHandleFeeResultMsg")
    public ServiceHandleFeeResultMsg serviceHandleFee(
        @WebParam(name = "ServiceHandleFeeRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ServiceHandleFeeRequestMsg")
        ServiceHandleFeeRequestMsg serviceHandleFeeRequestMsg);

    /**
     * 
     * @param queryTransferLogRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.QueryTransferLogResultMsg
     */
    @WebMethod(operationName = "QueryTransferLog", action = "QueryTransferLog")
    @WebResult(name = "QueryTransferLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "QueryTransferLogResultMsg")
    public QueryTransferLogResultMsg queryTransferLog(
        @WebParam(name = "QueryTransferLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "QueryTransferLogRequestMsg")
        QueryTransferLogRequestMsg queryTransferLogRequestMsg);

    /**
     * 
     * @param queryAdjustmentLogRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.QueryAdjustmentLogResultMsg
     */
    @WebMethod(operationName = "QueryAdjustmentLog", action = "QueryAdjustmentLog")
    @WebResult(name = "QueryAdjustmentLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "QueryAdjustmentLogResultMsg")
    public QueryAdjustmentLogResultMsg queryAdjustmentLog(
        @WebParam(name = "QueryAdjustmentLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "QueryAdjustmentLogRequestMsg")
        QueryAdjustmentLogRequestMsg queryAdjustmentLogRequestMsg);

    /**
     * 
     * @param modifyVoucherStateRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.ModifyVoucherStateResultMsg
     */
    @WebMethod(operationName = "ModifyVoucherState", action = "ModifyVoucherState")
    @WebResult(name = "ModifyVoucherStateResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ModifyVoucherStateResultMsg")
    public ModifyVoucherStateResultMsg modifyVoucherState(
        @WebParam(name = "ModifyVoucherStateRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ModifyVoucherStateRequestMsg")
        ModifyVoucherStateRequestMsg modifyVoucherStateRequestMsg);

    /**
     * 
     * @param balanceToValidityRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.BalanceToValidityResultMsg
     */
    @WebMethod(operationName = "BalanceToValidity", action = "BalanceToValidity")
    @WebResult(name = "BalanceToValidityResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "BalanceToValidityResultMsg")
    public BalanceToValidityResultMsg balanceToValidity(
        @WebParam(name = "BalanceToValidityRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "BalanceToValidityRequestMsg")
        BalanceToValidityRequestMsg balanceToValidityRequestMsg);

    /**
     * 
     * @param transInPpsPosRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.TransInPpsPosResultMsg
     */
    @WebMethod(operationName = "TransInPpsPos", action = "TransInPpsPos")
    @WebResult(name = "TransInPpsPosResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "TransInPpsPosResultMsg")
    public TransInPpsPosResultMsg transInPpsPos(
        @WebParam(name = "TransInPpsPosRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "TransInPpsPosRequestMsg")
        TransInPpsPosRequestMsg transInPpsPosRequestMsg);

    /**
     * 
     * @param exchangeAccountRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.ExchangeAccountResultMsg
     */
    @WebMethod(operationName = "ExchangeAccount", action = "ExchangeAccount")
    @WebResult(name = "ExchangeAccountResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ExchangeAccountResultMsg")
    public ExchangeAccountResultMsg exchangeAccount(
        @WebParam(name = "ExchangeAccountRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ExchangeAccountRequestMsg")
        ExchangeAccountRequestMsg exchangeAccountRequestMsg);

    /**
     * 
     * @param modSubBillCycleTypeRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.ModSubBillCycleTypeResultMsg
     */
    @WebMethod(operationName = "ModSubBillCycleType", action = "ModSubBillCycleType")
    @WebResult(name = "ModSubBillCycleTypeResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ModSubBillCycleTypeResultMsg")
    public ModSubBillCycleTypeResultMsg modSubBillCycleType(
        @WebParam(name = "ModSubBillCycleTypeRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "ModSubBillCycleTypeRequestMsg")
        ModSubBillCycleTypeRequestMsg modSubBillCycleTypeRequestMsg);

    /**
     * 
     * @param adjustSubAccountRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.AdjustSubAccountResultMsg
     */
    @WebMethod(operationName = "AdjustSubAccount", action = "AdjustSubAccount")
    @WebResult(name = "AdjustSubAccountResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "AdjustSubAccountResultMsg")
    public AdjustSubAccountResultMsg adjustSubAccount(
        @WebParam(name = "AdjustSubAccountRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "AdjustSubAccountRequestMsg")
        AdjustSubAccountRequestMsg adjustSubAccountRequestMsg);

    /**
     * 
     * @param subAccountRechargeRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.SubAccountRechargeResultMsg
     */
    @WebMethod(operationName = "SubAccountRecharge", action = "SubAccountRecharge")
    @WebResult(name = "SubAccountRechargeResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "SubAccountRechargeResultMsg")
    public SubAccountRechargeResultMsg subAccountRecharge(
        @WebParam(name = "SubAccountRechargeRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "SubAccountRechargeRequestMsg")
        SubAccountRechargeRequestMsg subAccountRechargeRequestMsg);

    /**
     * 
     * @param voucherRechargeBySeqRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.VoucherRechargeBySeqResultMsg
     */
    @WebMethod(operationName = "VoucherRechargeBySeq", action = "VoucherRechargeBySeq")
    @WebResult(name = "VoucherRechargeBySeqResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherRechargeBySeqResultMsg")
    public VoucherRechargeBySeqResultMsg voucherRechargeBySeq(
        @WebParam(name = "VoucherRechargeBySeqRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "VoucherRechargeBySeqRequestMsg")
        VoucherRechargeBySeqRequestMsg voucherRechargeBySeqRequestMsg);

    /**
     * 
     * @param bonusValidityRequestMsg
     * @return
     *     returns com.huawei.ocs55.acctmgr.BonusValidityResultMsg
     */
    @WebMethod(operationName = "BonusValidity", action = "BonusValidity")
    @WebResult(name = "BonusValidityResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "BonusValidityResultMsg")
    public BonusValidityResultMsg bonusValidity(
        @WebParam(name = "BonusValidityRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "BonusValidityRequestMsg")
        BonusValidityRequestMsg bonusValidityRequestMsg);

}
