
package com.huawei.ocs12.accountmgrservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CBSInterfaceAccountMgrServicePortType", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CBSInterfaceAccountMgrServicePortType {


    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.QueryBonusHistoryResultMsg
     */
    @WebMethod(operationName = "QueryBonusHistory", action = "QueryBonusHistory")
    @WebResult(name = "QueryBonusHistoryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public QueryBonusHistoryResultMsg queryBonusHistory(
        @WebParam(name = "QueryBonusHistoryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        QueryBonusHistoryRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.VoucherRechargeBySeqResultMsg
     */
    @WebMethod(operationName = "VoucherRechargeBySeq", action = "VoucherRechargeBySeq")
    @WebResult(name = "VoucherRechargeBySeqResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public VoucherRechargeBySeqResultMsg voucherRechargeBySeq(
        @WebParam(name = "VoucherRechargeBySeqRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        VoucherRechargeBySeqRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.PaymentEnquiryResultMsg
     */
    @WebMethod(operationName = "PaymentEnquiry", action = "PaymentEnquiry")
    @WebResult(name = "PaymentEnquiryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public PaymentEnquiryResultMsg paymentEnquiry(
        @WebParam(name = "PaymentEnquiryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        PaymentEnquiryRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.TransferAccountResultMsg
     */
    @WebMethod(operationName = "TransferAccount", action = "TransferAccount")
    @WebResult(name = "TransferAccountResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public TransferAccountResultMsg transferAccount(
        @WebParam(name = "TransferAccountRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        TransferAccountRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.QueryTransferLogResultMsg
     */
    @WebMethod(operationName = "QueryTransferLog", action = "QueryTransferLog")
    @WebResult(name = "QueryTransferLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public QueryTransferLogResultMsg queryTransferLog(
        @WebParam(name = "QueryTransferLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        QueryTransferLogRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.ModSubBillCycleTypeResultMsg
     */
    @WebMethod(operationName = "ModSubBillCycleType", action = "ModSubBillCycleType")
    @WebResult(name = "ModSubBillCycleTypeResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public ModSubBillCycleTypeResultMsg modSubBillCycleType(
        @WebParam(name = "ModSubBillCycleTypeRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        ModSubBillCycleTypeRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.CumulateEnquiryResultMsg
     */
    @WebMethod(operationName = "CumulateEnquiry", action = "CumulateEnquiry")
    @WebResult(name = "CumulateEnquiryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public CumulateEnquiryResultMsg cumulateEnquiry(
        @WebParam(name = "CumulateEnquiryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        CumulateEnquiryRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.AdjustAccountResultMsg
     */
    @WebMethod(operationName = "AdjustAccount", action = "AdjustAccount")
    @WebResult(name = "AdjustAccountResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public AdjustAccountResultMsg adjustAccount(
        @WebParam(name = "AdjustAccountRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        AdjustAccountRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.TransInPpsPosResultMsg
     */
    @WebMethod(operationName = "TransInPpsPos", action = "TransInPpsPos")
    @WebResult(name = "TransInPpsPosResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public TransInPpsPosResultMsg transInPpsPos(
        @WebParam(name = "TransInPpsPosRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        TransInPpsPosRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.QueryCallHistoryResultMsg
     */
    @WebMethod(operationName = "QueryCallHistory", action = "QueryCallHistory")
    @WebResult(name = "QueryCallHistoryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public QueryCallHistoryResultMsg queryCallHistory(
        @WebParam(name = "QueryCallHistoryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        QueryCallHistoryRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.ServiceHandleFeeResultMsg
     */
    @WebMethod(operationName = "ServiceHandleFee", action = "ServiceHandleFee")
    @WebResult(name = "ServiceHandleFeeResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public ServiceHandleFeeResultMsg serviceHandleFee(
        @WebParam(name = "ServiceHandleFeeRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        ServiceHandleFeeRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.VoucherEnquiryByPINResultMsg
     */
    @WebMethod(operationName = "VoucherEnquiryByPIN", action = "VoucherEnquiryByPIN")
    @WebResult(name = "VoucherEnquiryByPINResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public VoucherEnquiryByPINResultMsg voucherEnquiryByPIN(
        @WebParam(name = "VoucherEnquiryByPINRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        VoucherEnquiryByPINRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.QueryBalanceResultMsg
     */
    @WebMethod(operationName = "QueryBalance", action = "QueryBalance")
    @WebResult(name = "QueryBalanceResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public QueryBalanceResultMsg queryBalance(
        @WebParam(name = "QueryBalanceRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        QueryBalanceRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.SubAccountRechargeResultMsg
     */
    @WebMethod(operationName = "SubAccountRecharge", action = "SubAccountRecharge")
    @WebResult(name = "SubAccountRechargeResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public SubAccountRechargeResultMsg subAccountRecharge(
        @WebParam(name = "SubAccountRechargeRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        SubAccountRechargeRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.VoucherRechargeResultMsg
     */
    @WebMethod(operationName = "VoucherRecharge", action = "VoucherRecharge")
    @WebResult(name = "VoucherRechargeResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public VoucherRechargeResultMsg voucherRecharge(
        @WebParam(name = "VoucherRechargeRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        VoucherRechargeRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.BalanceToValidityResultMsg
     */
    @WebMethod(operationName = "BalanceToValidity", action = "BalanceToValidity")
    @WebResult(name = "BalanceToValidityResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public BalanceToValidityResultMsg balanceToValidity(
        @WebParam(name = "BalanceToValidityRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        BalanceToValidityRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.ModifyVoucherStateResultMsg
     */
    @WebMethod(operationName = "ModifyVoucherState", action = "ModifyVoucherState")
    @WebResult(name = "ModifyVoucherStateResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public ModifyVoucherStateResultMsg modifyVoucherState(
        @WebParam(name = "ModifyVoucherStateRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        ModifyVoucherStateRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.VoucherEnquiryBySeqResultMsg
     */
    @WebMethod(operationName = "VoucherEnquiryBySeq", action = "VoucherEnquiryBySeq")
    @WebResult(name = "VoucherEnquiryBySeqResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public VoucherEnquiryBySeqResultMsg voucherEnquiryBySeq(
        @WebParam(name = "VoucherEnquiryBySeqRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        VoucherEnquiryBySeqRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.OneOffDeductionResultMsg
     */
    @WebMethod(operationName = "OneOffDeduction", action = "OneOffDeduction")
    @WebResult(name = "OneOffDeductionResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public OneOffDeductionResultMsg oneOffDeduction(
        @WebParam(name = "OneOffDeductionRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        OneOffDeductionRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.QueryAdjustmentLogResultMsg
     */
    @WebMethod(operationName = "QueryAdjustmentLog", action = "QueryAdjustmentLog")
    @WebResult(name = "QueryAdjustmentLogResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public QueryAdjustmentLogResultMsg queryAdjustmentLog(
        @WebParam(name = "QueryAdjustmentLogRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        QueryAdjustmentLogRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.PaymentResultMsg
     */
    @WebMethod(operationName = "Payment", action = "Payment")
    @WebResult(name = "PaymentResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public PaymentResultMsg payment(
        @WebParam(name = "PaymentRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        PaymentRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.ReversePaymentResultMsg
     */
    @WebMethod(operationName = "ReversePayment", action = "ReversePayment")
    @WebResult(name = "ReversePaymentResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public ReversePaymentResultMsg reversePayment(
        @WebParam(name = "ReversePaymentRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        ReversePaymentRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.AdjustSubAccountResultMsg
     */
    @WebMethod(operationName = "AdjustSubAccount", action = "AdjustSubAccount")
    @WebResult(name = "AdjustSubAccountResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public AdjustSubAccountResultMsg adjustSubAccount(
        @WebParam(name = "AdjustSubAccountRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        AdjustSubAccountRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.ExchangeAccountResultMsg
     */
    @WebMethod(operationName = "ExchangeAccount", action = "ExchangeAccount")
    @WebResult(name = "ExchangeAccountResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public ExchangeAccountResultMsg exchangeAccount(
        @WebParam(name = "ExchangeAccountRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        ExchangeAccountRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.VoucherRechargeEnquiryResultMsg
     */
    @WebMethod(operationName = "VoucherRechargeEnquiry", action = "VoucherRechargeEnquiry")
    @WebResult(name = "VoucherRechargeEnquiryResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public VoucherRechargeEnquiryResultMsg voucherRechargeEnquiry(
        @WebParam(name = "VoucherRechargeEnquiryRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        VoucherRechargeEnquiryRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.accountmgrservice.ActiveFirstResultMsg
     */
    @WebMethod(operationName = "ActiveFirst", action = "ActiveFirst")
    @WebResult(name = "ActiveFirstResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
    public ActiveFirstResultMsg activeFirst(
        @WebParam(name = "ActiveFirstRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgrmsg", partName = "part1")
        ActiveFirstRequestMsg part1);

}
