
package com.huawei.ocs12.accountmgrservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CBSInterfaceAccountMgrService", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/accountmgr", wsdlLocation = "file:/E:/OneDrive/09-tt/unieap/unieap-esb/src/main/resources/wsdl/ocs12/META-INF_AccountMgr/CBSInterfaceAccountMgrService.wsdl")
public class CBSInterfaceAccountMgrService
    extends Service
{

    private final static URL CBSINTERFACEACCOUNTMGRSERVICE_WSDL_LOCATION;
    private final static WebServiceException CBSINTERFACEACCOUNTMGRSERVICE_EXCEPTION;
    private final static QName CBSINTERFACEACCOUNTMGRSERVICE_QNAME = new QName("http://www.huawei.com/bme/cbsinterface/cbs/accountmgr", "CBSInterfaceAccountMgrService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/OneDrive/09-tt/unieap/unieap-esb/src/main/resources/wsdl/ocs12/META-INF_AccountMgr/CBSInterfaceAccountMgrService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CBSINTERFACEACCOUNTMGRSERVICE_WSDL_LOCATION = url;
        CBSINTERFACEACCOUNTMGRSERVICE_EXCEPTION = e;
    }

    public CBSInterfaceAccountMgrService() {
        super(__getWsdlLocation(), CBSINTERFACEACCOUNTMGRSERVICE_QNAME);
    }

    public CBSInterfaceAccountMgrService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CBSINTERFACEACCOUNTMGRSERVICE_QNAME, features);
    }

    public CBSInterfaceAccountMgrService(URL wsdlLocation) {
        super(wsdlLocation, CBSINTERFACEACCOUNTMGRSERVICE_QNAME);
    }

    public CBSInterfaceAccountMgrService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CBSINTERFACEACCOUNTMGRSERVICE_QNAME, features);
    }

    public CBSInterfaceAccountMgrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CBSInterfaceAccountMgrService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CBSInterfaceAccountMgrServicePortType
     */
    @WebEndpoint(name = "CBSInterfaceAccountMgrServiceSOAP11port_http")
    public CBSInterfaceAccountMgrServicePortType getCBSInterfaceAccountMgrServiceSOAP11PortHttp() {
        return super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/cbs/accountmgr", "CBSInterfaceAccountMgrServiceSOAP11port_http"), CBSInterfaceAccountMgrServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CBSInterfaceAccountMgrServicePortType
     */
    @WebEndpoint(name = "CBSInterfaceAccountMgrServiceSOAP11port_http")
    public CBSInterfaceAccountMgrServicePortType getCBSInterfaceAccountMgrServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/cbs/accountmgr", "CBSInterfaceAccountMgrServiceSOAP11port_http"), CBSInterfaceAccountMgrServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CBSINTERFACEACCOUNTMGRSERVICE_EXCEPTION!= null) {
            throw CBSINTERFACEACCOUNTMGRSERVICE_EXCEPTION;
        }
        return CBSINTERFACEACCOUNTMGRSERVICE_WSDL_LOCATION;
    }

}
