
package com.huawei.ocs12.productmgrservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CBSInterfaceProductMgrServicePortType", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CBSInterfaceProductMgrServicePortType {


    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.productmgrservice.QueryProductsByReplacingResultMsg
     */
    @WebMethod(operationName = "QueryProductsByReplacing", action = "QueryProductsByReplacing")
    @WebResult(name = "QueryProductsByReplacingResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
    public QueryProductsByReplacingResultMsg queryProductsByReplacing(
        @WebParam(name = "QueryProductsByReplacingRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
        QueryProductsByReplacingRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.productmgrservice.ReleaseProductResultMsg
     */
    @WebMethod(operationName = "ReleaseProduct", action = "ReleaseProduct")
    @WebResult(name = "ReleaseProductResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
    public ReleaseProductResultMsg releaseProduct(
        @WebParam(name = "ReleaseProductRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
        ReleaseProductRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.productmgrservice.QueryBrandsResultMsg
     */
    @WebMethod(operationName = "QueryBrands", action = "QueryBrands")
    @WebResult(name = "QueryBrandsResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
    public QueryBrandsResultMsg queryBrands(
        @WebParam(name = "QueryBrandsRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
        QueryBrandsRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.productmgrservice.QueryProductsBySubscribingResultMsg
     */
    @WebMethod(operationName = "QueryProductsBySubscribing", action = "QueryProductsBySubscribing")
    @WebResult(name = "QueryProductsBySubscribingResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
    public QueryProductsBySubscribingResultMsg queryProductsBySubscribing(
        @WebParam(name = "QueryProductsBySubscribingRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
        QueryProductsBySubscribingRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.productmgrservice.QueryProductsByNewSubscriberResultMsg
     */
    @WebMethod(operationName = "QueryProductsByNewSubscriber", action = "QueryProductsByNewSubscriber")
    @WebResult(name = "QueryProductsByNewSubscriberResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
    public QueryProductsByNewSubscriberResultMsg queryProductsByNewSubscriber(
        @WebParam(name = "QueryProductsByNewSubscriberRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
        QueryProductsByNewSubscriberRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.productmgrservice.QueryProductListInfoResultMsg
     */
    @WebMethod(operationName = "QueryProductListInfo", action = "QueryProductListInfo")
    @WebResult(name = "QueryProductListInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
    public QueryProductListInfoResultMsg queryProductListInfo(
        @WebParam(name = "QueryProductListInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
        QueryProductListInfoRequestMsg part1);

    /**
     * 
     * @param part1
     * @return
     *     returns com.huawei.ocs12.productmgrservice.QueryProductInformationResultMsg
     */
    @WebMethod(operationName = "QueryProductInformation", action = "QueryProductInformation")
    @WebResult(name = "QueryProductInformationResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
    public QueryProductInformationResultMsg queryProductInformation(
        @WebParam(name = "QueryProductInformationRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/cbs/productmgrmsg", partName = "part1")
        QueryProductInformationRequestMsg part1);

}
